### ISSUE TITLE
Some files are silently skipped from downloading

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#103]
While testing the progress bar code, I came across another bug in the core wget2 logic. Sometimes, a file is completely skipped by Wget2 for download. To reproduce, you can use the following command:

```
wget2 --progress bar http://ipv4.download.thinkbroadband.com/5MB.zip http://ipv4.download.thinkbroadband.com/10MB.zip http://ipv4.download.thinkbroadband.com/20MB.zip http://ipv6.download.thinkbroadband.com/50MB.zip
```

You will see that the last link is not downloaded at all.

**Comment by darnir** [comment]
This bug seems to have been around for a long time now. Because it is present from before the progress bar changes were merged.

With the last PR I sent, #102, this bug has started becoming more visible.

**Comment by rockdaboot** [comment]
```
Failed to write 237 bytes (101)
```
Does the server eventually accept no more than 3 connections at a time ?

**Comment by rockdaboot** [comment]
http://ipv6.download.thinkbroadband.com is currently not reachable (errno 101)

**Comment by rockdaboot** [comment]
But http://ipv4.download.thinkbroadband.com/50MB.zip works ;-)

**Comment by darnir** [comment]
That's interesting. I hadn't spent any time debugging this. Decided to open an issue so I remember to look into it later. 

Maybe we should improve the error reporting for such cases? Especially since it creates a slot for the progress bar but does not register a context. 

If the server is not reachable, then we should be able to generate a "Cannot connect error" instead of a generic could not write XX bytes.
