### ISSUE TITLE
+ symbol in Path gets replaced with ' '

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#109]
Example URI: https://launchpad.net/libmetalink/trunk/libmetalink-0.1.3/+download/libmetalink-0.1.3.tar.bz2

In iri.c (wgte_iri_unescape_inline):
```
		} else if (*s == '+') {
			*d++ = ' ';
			s++;
			ret = src;
			continue;
		}
```

This fragment is looking for the '+' character and replacing it with a space (' '). As you can see, this would cause a problem in the above URI where there is a + character in the path component. 

Is this check even necessary? From a cursory reading of RFC 3986, I see that the '+' character may occur in the scheme, but even then I see no mention anywhere of replacing it with a space.

All tests continue to pass after I removed the check locally. If this is required, can you please add some tests for it?

**Comment by rockdaboot** [comment]
The unescape 'decodes' URL encoding. '+' becomes a space, if you want '+' use percent encoding.
see http://ascii.cl/url-decoding.htm (enter the URL ans see + -> space).
also see https://en.wikipedia.org/wiki/Percent-encoding (The application/x-www-form-urlencoded type).
Basically it depends, where URL comes from. IMO, we should handle it as wget, curl and browsers do it.

**Comment by rockdaboot** [comment]
And test cases... now that we have test coverage, we should go through all the API and add test cases to cover everything - but this is a long process and we should attract more developers by releasing wget2 soon (even a pre-release, e.g. for Debian would be a good starter).

**Comment by rockdaboot** [comment]
Maybe we just have to care for +->space when extracting URLs from HTML !?

**Comment by rockdaboot** [comment]
Now: http://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20
Just for query (and fragment ?).
So it's usage in wget_iri_parse is wrong indeed. There are thousands of test cases for correct URL encoding/decoding - we should just adopt one of them and use it as test data.

**Comment by darnir** [comment]
True. Just for the query / fragment part we need to replace the + with a space. Else it should remain so. 

P.S. About developers and test cases, I completely agree. We need to fix a couple more things before though. I'll try making a list tomorrow about basic things that require fixing before a pre-release.

**Comment by rockdaboot** [comment]
I took a look at url parsing test suites. They differ very much in corner cases. So we have to hand-edit these suites a lot to fit for libwget. I suggest that we extend our tests with all kind of non-corner cases (e.g. like the + in different parts of the url). At some later point we could strive for e.g. being Firefox and/or Chromium compatible even in the corner cases. I start adding some new cases now and fix wget_iri_parse as appropriate.
