### ISSUE TITLE
LIBWGET_EXPORT must be preceed the prototypes to work on Windows (MSVC)

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#122]
Currently we have
```
void
	wget_millisleep(int ms) LIBWGET_EXPORT;
```

but to compile on Windows it must be
```
LIBWGET_EXPORT void
	wget_millisleep(int ms);
```

Currently I added checking for LIBWGET_STATIC to define LIBWGET_EXPORT to be empty.
Thanks to Gisle Vanem for his suggestion.

**Comment by darnir** [comment]
Anything that is required to be done for this issue?

**Comment by rockdaboot** [comment]
No, it just have to be done. Maybe we rename LIBWGET_EXPORT to WGETAPI !?
This is like other libs do it.
