### ISSUE TITLE
Progress percentage not updated on HTTP/2

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#126]
When downloading a file over HTTP/2, the progress bar is correctly updated, but the %age display remains at 0.

**Comment by rockdaboot** [comment]
Not here... check the server's content-length header...

**Comment by darnir** [comment]
Fixed by 0117ec4ff5334f6221460aa7f15977397f8d0d41.

The issue was the same as the one in the above commit. ratio was being truncated to 0 due to an integer overflow when downloading a very large file (20GB and above)
