### ISSUE TITLE
Documentation of the wget2 tool

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#13]
Fetch the doc/wget.texi from Wget master branch and amend it

**Comment by darnir** [comment]
Do we plan to continue using the texi files? If we had to, I'd much rather use TeX directly, it can be converted to a whole bunch of formats. Else, there are other decently good formats to write documentation in too.

**Comment by giuseppe** [comment]
This also depends on wget2 being GNU or not. Another advantage though is that the existing documentation can be used as it is.

**Comment by juaristi** [comment]
One significant improvement over Wget is probably the code documentation. I'm documenting the low-level functions such as those in hasfile.c, during these days, and I'm using GTK-Doc, which is already built into the Makefiles.

Does GNU concern about which documentation tools you use (e.g. GTK-Doc)?

**Comment by rockdaboot** [comment]
The API is currently GTK-DOC, but not not much documented so far. Introducing LIBWGET_EXPORT let GTK-DOC fail to scan libwget.h. GTK-DOC is a pretty hackish perl extraction. Meanwhile I am playing with doxygen, which seems pretty complete and also understands markdown. The reason I took GTK-DOC in 2012 were some problems with doxygen, which seem to be fixed meanwhile.

@Darshit I would not start using TeX directly, what do the others think ?
I don't see a problem to use the existing Texi documentation for the Wget2 tool. Just as a quick starter.

**Comment by darnir** [comment]
Doxygen is in fact something that I am completely in favour of. I've used it once before and it has worked pretty well.

**Comment by rockdaboot** [comment]
Have doxygen basically working, needs of course some tweaking. I'll push it maybe tomorow.
Do we have a Wget logo ? Just found a generic one with a GNU - is that the official one ?

**Comment by rockdaboot** [comment]
The basics are pushed. As an example, I transformed the docs in libwget/list.c so far. Doxygen is automatically detected, html + man pages are generated, man pages are installed via make install.

I didn't manage to have examples/*.c appear in the html pages. Also, README.md as the main page does not appear so far. Both are configured in the doxygen config file. Any ideas ?
