### ISSUE TITLE
Support Environment Variable for config file

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#132]
Wget2 should try to follow the XDG base directory specifications for configuration and data files.

Also, we should have an option to set the user config file via an environment variable similar to `WGETRC`

Also, some options in Wget 1.x are not supported in Wget2 and vice versa, how are we handling these cases?

I was unable to find any information in the manual pages for wget2 about this. I think this is critical information that must be explained before the Alpha release.

**Comment by rockdaboot** [comment]
> Wget2 should try to follow the XDG base directory specifications for configuration and data files.

Not a bug, more of a wishlist. For the alpha release we follow Wget1.x conventions.

> Also, we should have an option to set the user config file via an environment variable similar to WGETRC.

Yes.

> Also, some options in Wget 1.x are not supported in Wget2 and vice versa, how are we handling these cases?

Explained/documented in the [wiki](https://github.com/rockdaboot/wget2/wiki)
We could move that into the docs as .md file.

**Comment by darnir** [comment]
Thanks for adding the last commit, reading $WGETRC and using xdg-dirs. One more thing pending is tilde expansion for filenames, especially hsts-file, ocsp-file and tsl-session. I'm working on writing that using `wordexp`. I'll send a patch soon

**Comment by rockdaboot** [comment]
glob() should be used IMO. It is covered by gnulib... and don't we use it already ?

**Comment by rockdaboot** [comment]
see options.c/get_home_dir(void)

**Comment by darnir** [comment]
`man glob` says this:

> The glob() function searches for all the pathnames matching pattern according to the rules used by the shell (see glob(7)).  No tilde expansion
>        or parameter substitution is done; if you want these, use wordexp(3).

Hence, the choice to use `wordexp`.  I tried setting `hsts-file = ~/.config/wget/hsts-file` in my wgetrc and passed it to wget2. It tried to access a file in a directory called "~", so I guess we are not performing tilde expansion when we read from the config file. The shell does it for us when we use the command line options

**Comment by darnir** [comment]
Okay, reading the man page further shows that the first line in there is wrong. `glob()` can indeed perform tilde expansion when used with `GLOB_TILDE`. Maybe should file a bug with then to change the man page

**Comment by darnir** [comment]
In light of this, I'll change my WIP to use glob instead of wordexp since that gives us better gnulib support as well

**Comment by darnir** [comment]
Okay, I spent more time reading the manual properly. The issue with using `glob()` is that it will perform the expansion *only* if the file already exists. The user may write the configuration file as:
`hsts-file=~/.nonexistent_hsts`
And Wget2 should create the file if it does not exist. However, glob() will fail to match this string and hence return "~/.nonexistent_hsts" or a `GLOB_NOMATCH` based on the flags. Instead, we should directly use `wordexp()` which is also available through gnulib to perform the tilde expansion irrespective of whether the file actually exists.

**Comment by rockdaboot** [comment]
I can't find wordexp() anywhere in gnulib/.
~ Only makes sense as first character... as shortcut for the home directory, see get_home_dir().
So a little function should do it: check wether name begins with ~ and if so, replace ~ with home dir.
If we don't have a home dir: skip loading or error&exit if file was explicitly given by --config/--config-file.

**Comment by darnir** [comment]
> So a little function should do it: check wether name begins with ~ and if so, replace ~ with home dir.
> If we don't have a home dir: skip loading or error&exit if file was explicitly given by --config/--config-file.

A user may also pass ~bob/.wget-hsts as a filename. Now we need to test for both the first and the second character to identify which home directory to point to. 
Another advantage of wordexp is shell style variable expansion. This allows the user to use environment variables in wgetrc for such filenames as well.

It's interesting that even I can't find wordexp in gnulib. Because see these links:
https://www.gnu.org/software/gnulib/manual/gnulib.html#wordexp_002eh
https://www.gnu.org/software/gnulib/manual/html_node/wordexp.html

It's mentioned in the gnulib documentation. Which is why I figured, we can use it without much trouble. I'll send a mail on bug-gnulib asking about this discrepancy

**Comment by darnir** [comment]
Aah! I just noticed, it says, "Gnulib module: -" to indicate that such a function exists but has not been ported yet.

Maybe we will have to use Glob instead then. I'll write it up sometime soon

**Comment by rockdaboot** [comment]
I didn't know about ~bob to get bob's homedir.

**Comment by darnir** [comment]
Yes, there's always some hidden conditions to handle in all these cases. Which is why I wanted to offload the entire thing to a library which handles all the cases. However, we will have to write this condition ourselves. I have a hectic week ahead, so will write it up as soon as I get some time
