### ISSUE TITLE
Handling of configuration files

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#133]
Right now Wget2 reads `/etc/wgetrc` and then the user's local wgetrc file based on `$WGETRC` variable, `$XDG_CONFIG_HOME/.wgetrc` or `~/.wgetrc` as its configuration file.

This poses a new problem for both Wget and Wget2:
Options that are not compatible across the two versions of Wget, and how they should be handled.

For example, an existing Wgetrc file may have the option: `xattr = on` or `progress = dot` These options are not currently supported by Wget2 and as a result, wget2 will fail on startup.

Similarly, for wget2, I'd like to have the options `progress = bar` or `ocsp-file = somefile` which are not supported by Wget 1.x hence causing that fail on startup.

One of the chief problems I see here is the fact that we are trying to support the same config file for both versions of Wget. A few solutions were discussed on the comments for commit 6b2d929617b14aa7ffac33fb79843cbc3c1e6287

- Wget2 potentially uses different config file, `~/.wget2rc` and similarly environment variable, `$WGET2RC`
- Both wget and wget2 are changed to fail on an invalid config option but to print a warning
- Both wget and wget2 support _including_ a config file from another config file.
- Modify syntax of wgetrc to have versioned commands

Each of these solutions have their pros and cons. However, we must decide on one ASAP before the alpha release. An important aspect to remember is that the `.wgetrc` **MUST** remain backward compatible.

1. Using different configuration files is a nice clean solution. No change required in either program. However, this increases configuration duplication and is more effort for the end user
2. I do not like the idea of ignoring and printing a warning. If Wget / Wget2 print a warning on every startup, the users will be trained in ignoring the warnings and will never pay any heed to it. That just makes this excess data printed to stdout.
3. Including a config file is a clean solution, but increases fragmentation. It now requires a user to maintain 3 config files. A master (common) wget config and a specific config for each version. Also, this must be done along with the first option to split the configuration files read by each
4. Versioned commands in wgetrc will require changes to both Wget and Wget2 and it must be done such that existing wgetrc files just work. One way to implement this would be to add a "v1" or "v2" after the command syntax in wgetrc to denote that this specific command should only be executed on the given version. By default commands are always executed.

**Comment by rockdaboot** [comment]
Versioning is IMO not an Option since older versions of wget will fail. 
Let's stick with wget2's own config file name/var with also reading wget1's config, but skipping unknown commands in the latter. That let's wget1 work smoothly. Printing a warning in wget2 isn' t that bad... We are going to add these missing options sooner or later.

**Comment by darnir** [comment]
Then we need to bring some option parity between wget and wget2. As of now, I think atleast the progress option isn't compatible across both, but it exists as an option nonetheless.

**Comment by rockdaboot** [comment]
progress seems to be compatible, though not fully implemented in wget2.
Both, wget and wget2, understand `--progress=bar`.

I just thought again about versioning...
Putting wget2-tagged instructions into comments of .wgetrc lets wget1.x work without problems. Together with wget2 issuing warnings about 'not implemented' features, that could work. Later (maybe non alpha-release) we can change that behavior from warning -> error.

**Comment by darnir** [comment]
One problem with this would be that it binds Wget2 to use the syntax and command line options of Wget 1.x. At some point we may decide to diverge because something else is clearer. I would support being able to read the Wget 1.x config files through a separate parser (very far in the future), but being able to have its own syntax for command line options. 

As a result, I think using an entirely separate wget2rc file makes the most sense. Yes, it will require duplication of `wgetrc` commands for many, but it seems like the safest option that doesn't bind Wget2 to anything rom the past.

**Comment by juaristi** [comment]
What happens if `wget2rc` does not exist? You continue as if there was no config file, or you try to read `wgetrc`?

**Comment by rockdaboot** [comment]
@juaristi If we go with Darshit's proposal, wgetrc isn't read at all (except someone specifies it via command line option --config/--config-file).

Of course someone could include wgetrc from wget2rc. In this case we need an option to relax parsing, e.g. either warn, ignore or error on unknown options.

```
unknown-config=warn
inlcude ~/wgetrc
unknown-config=error
```

Such an option is also useful, if we experiment with 2 different versions of wget2. Having a new option in wget2rc with unknown-config=warn in front of it, and the 'stock' (e.g. packaged version) still works.

**Comment by darnir** [comment]
I had the same ideas as Tim stated. That sounds like the best way forward.
We should not depend on Wget 1.x config files unless the user explicitly
asks to use it.

Thanking You,
Darshit Shah

**Comment by rockdaboot** [comment]
Slightly amended suggestion:

**default**
Read SYSTEM_WGETRC and ~/.wgetrc in that order, ignoring all unknown options.
Then read SYSTEM_WGET2RC and ~/.wget2rc.
With this we make wget->wget2 transition very easy.
Caveat: additional file I/O, we can never retreat from that behavior without breaking working installations.

**--config-file=file**
We *additionally* read from `file` after doing the above.

**--config-file=NULL**
We do not read any config files resp. internally reset the config variables.

**--config-file=NULL --config-file=file**
Just read `file`.

**--config-file=file --config-file=NULL**
Don't read any file at all.

Technically, we would create a list of config files first with [SYSTEM_WGETRC ~/.wgetrc SYSTEM_WGET2RC ~/.wget2rc] then traverse the CLI options, adding each file given by --config-file. When seeing a NULL file, we reset the list to `empty` and continue.

The inclusion of SYSTEM_WGETRC and ~/.wgetrc is debatable (please give me your opinions), but I would start to implement the above algorithm.
