### ISSUE TITLE
ANSI sequences on Windows

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#138]
As @gvanem stated, Windows doesn't interpret ANSI sequences.

Win10 supports ANSI, but it has to be enabled (https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032%28v=vs.85%29.aspx).

In the library code, only bar.c uses ANSI sequences for cursor positioning.
We have to create functions (static+inline, for use in bar.c only) for each functionality, so that we can use #ifdef _WIN32 to use Windows functions instead of ANSI sequences.

@gvanem Do you agree or is there a better approach ?

Wget2 sources just use ANSI color sequences in src/log.c in three places, that should be easy going.

**Comment by gvanem** [comment]
> Win10 supports ANSI, but it has to be enabled

I tried the first example therein; it doesn't work unless the Console properties is set to *not* `use older console functions`. Furthermore `GetLastError()` gives no error if `SetConsoleMode()` fails.
And your code assumes a black console background; the magenta foreground looks terrible on a blue background. Add some `struct config::color_*` for that?

> In the library code, only bar.c uses ANSI sequences for cursor positioning.

But `bar.c` needs threading which doesn't work with PthreadsWin. So I've not tested the *Console Virtual Terminal* stuff there. But IMHO, `wget_bar_update(bar)` should then be called periodically.

>  we can use #ifdef _WIN32 to use Windows functions instead of ANSI sequences.

To reduce the number of `#ifdef _WIN32`, maybe just add (an inline) function `wget_ANSI_printf()` to `libwget/wget.h` and add a `libwget/console.c`?

**Comment by gvanem** [comment]
Besides using ANSI-sequences directly is such archaic beast from the 1970's. In some projects of [mine](https://github.com/gvanem/EnvTool/blob/master/src/color.c) I'm printing with colours like this:
```
/* will print to stdout with 'Hello' mapped to colour 4 (see below) and
 * 'world' mapped to colour 2. 
 */
C_printf ("~4Hello ~2world~0.\n"); 
```
The result will look the same for MSVC and CygWin (which do support ANSI internally).

**Comment by rockdaboot** [comment]
That's just a wrapper !? What about cursor positioning, which is my main concern...
Also, we need no general color support, just for complete lines and atomic if possible (without ugly locks).

**Comment by rockdaboot** [comment]
@gvanem (If you click 'watch' for this project, I don't have to ping you via @gvanem).
I added a new branch 'mscolor' with some abstractions for WIN32.
The code is very likely not complete and needs adjustments, please test and amend (I can only test on Linux with MinGW which gives no colors any more right now).
Once we are satisfied, I merge it into master.

**Comment by gvanem** [comment]
I'm *watching* this repo now. I took a look at `console.c`. It looks fine, will test it later.

**Comment by gvanem** [comment]
I've been working on an almost full ANSI-decoder for native Windows (MSVC, MinGW, clang). But it would help me if I understood what the progress-bar should look like (on Linux). 
I don't quite understand this `bar.c` code:
```
	// CSI s:    Save cursor
	// CSI <n>S: Scroll up whole screen
	// CSI <n>A: Cursor up
	// CSI <n>G: Cursor horizontal absolute
	// CSI 0J:   Clear from cursor to end of screen
	// CSI 31m:  Red text color
	printf("\033[s\033[1S\033[%dA\033[1G\033[0J\033[31m", bar->nslots + 1);
```

Does the `[nA` sequence mean there should be 1 bar per thread? Thus the whole thing with `--max-threads=2` should look like:
```
NUL                    85% [------------------------->            ]   180.54K
NUL                    94% [--------------------------------->    ]   200.78K
```
It would help with a YouTube video of Wget2 in operation.

**Comment by rockdaboot** [comment]
Yes, 1 bar per thread.
```
$ src/wget2 --progress bar http://ovh.net/files/10Mb.dat http://ovh.net/files/20Mb.dat
10Mb.dat             100% [=========================================================================================================================>]    1.19M
20Mb.dat             100% [=========================================================================================================================>]     223 
                          [Files: 1  Bytes: 1.19M  Redirects: 0  Todo: 0                                                                             ]
```

Lol, I never use the progress bar... but obviously values on the summary line are incorrect. I know it was working once... and these things pop up again and again... and nobody cares ... but basically this is not my battle ground. Just eye-candy for me. Why not having a real graphical output (X11, Windows) !? Optionally compilable, so packagers could have a wget2-ui command or something.

**Comment by rockdaboot** [comment]
Correction: The values are maybe correct... the server doesn't not deliver the expected file size and the 20Mb.dat errors.

**Comment by gvanem** [comment]
And in what colour is the bar? All I get is the default console colour. 

Testing with 2 (different or equal) URLS doesn't work here though 😢 .
But this doesn't seems to be related to the progress-bar:
```
wget2.exe  -O NUL http://ipv4.download.thinkbroadband.com:8080/5MB.zip http://ovh.net/fil es/10Mb.dat
[1] Downloading 'http://ovh.net/files/10Mb.dat' ...
[0] Downloading 'http://ipv4.download.thinkbroadband.com:8080/5MB.zip' ...
[0] Downloading 'http://ipv4.download.thinkbroadband.com:8080/5MB.zip' ...
Just got 142594 of 1250000 bytes
HTTP response 200 OK
```
Then hangs forever. I assume that's the 1st. Note, the first URL is printed twice ❓

**Comment by gvanem** [comment]
*Edit*: This seems to be related to `-O NUL` once again...

**Comment by rockdaboot** [comment]
```
$ ../src/wget2 -O /dev/null http://ipv4.download.thinkbroadband.com:8080/5MB.zip http://ovh.net/files/10Mb.dat
[1] Downloading 'http://ovh.net/files/10Mb.dat' ...
[0] Downloading 'http://ipv4.download.thinkbroadband.com:8080/5MB.zip' ...
HTTP response 200 OK

HTTP response 200 OK
```

Looks fine on Linux... what about without -O NUL ?

**Comment by gvanem** [comment]
> . what about without -O NUL ?

That works fine.

**Comment by rockdaboot** [comment]
Try with -d. I can't see any code differences between Win32 and Linux.

**Comment by gvanem** [comment]
> That works fine.

But not always. It depends on `--debug` and whether `stdout/stderr` is redirected. I don't get it.
