### ISSUE TITLE
Wget2 creates .wget_ocsp and .wget_ocsp_hosts files in $PWD

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#14]
As I understand these files are to allow Wget to realize during a future run which certificates it has already checked. However, it always creates these files in the $PWD while they should be in $HOME

**Comment by rockdaboot** [comment]
Feel free to change it.
I am pretty busy, being at the PC just from time to time.

**Comment by darnir** [comment]
I will. I should have time later today, so I'll write up a patch. Also, add
an option to specify the wgetrc file from the command line

Thanking You,
Darshit Shah
