### ISSUE TITLE
Read and write time_t as long long int, e.g. in hpkp.c

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#146]
Currently we use long int (format specifier %ld or %lu) which reduces time_t to 32 bits on systems where 'long int' just has 32bit. This is not enough, see https://en.wikipedia.org/wiki/Year_2038_problem.

Better would be to use 'long long int' which has 64 bits even on several (not all though) 32 bit systems.
Bad luck for systems where no integer type with more then 32 bits exists.

**Comment by rootkea** [comment]
I think this can be achieved simply by typedefing `long long int` to `time_t` overwriting it's initial typedef to  `__time_t` in `time.h`

But again `time_t` can be in multiple files so typedefing it to `long long int` is not elegant. May be we should do that in a separate header file which gets included in all of the *.c files. How about `wget.h`?

**Comment by rootkea** [comment]
I'm mostly worried about usage of variables declared of type `_time_t` as now we need to find all of those io functions and change `%ld` or `%lu` to `%ll` in all the source files.

**Comment by rockdaboot** [comment]
No typedef'ing is needed. Storing via printf-style function is simple (%lld + casting). Scanf'ing is a bit more overhead. We could read the value into a string and convert that with strtoll(), which is covered by gnulib for portability.

**Comment by gvanem** [comment]
With this patch, *clang-cl* gives no warnings:
```
--- a/libwget/hpkp.c 2017-03-20 20:01:51
+++ b/libwget/hpkp.c 2017-03-23 13:47:09
@@ -387,9 +387,13 @@
                        buf[--buflen] = 0;

                if (*linep != '*') {
+                       long long _created, _max_age;
+
                        wget_hpkp_db_add(hpkp_db, &hpkp);

-                       if (sscanf(linep, "%255s %d %ld %ld", host, &include_subdomains, &created, &max_age) == 4) {
+                       if (sscanf(linep, "%255s %d %lld %lld", host, &include_subdomains, &_created, &_max_age) == 4) {
+                               created = (time_t) _created;
+                               max_age = (time_t) _max_age;
                                if (max_age && (created + max_age) >= now) {
                                        hpkp = wget_hpkp_new();
                                        hpkp->host = wget_strdup(host);
```
I'm not sure if signed-time matters though.
