### ISSUE TITLE
Use --no-proxy for wget2 invocation in test suite

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#148]
If we don't, environment proxy settings might interfere the tests and lead to unexpected timeouts and failures.

**Comment by rootkea** [comment]
But as per `wget2 -help`, wget2 doesn't support `--no-proxy` option. So should we implement one for `wget2`? AFAIK `wget` has this option but I guess it doesn't use it to exclude few urls from using proxy but rather doesn't use proxy for all urls. Correct me if I'm wrong.

**Comment by rockdaboot** [comment]
It support --proxy (default: on). All boolean options can be specified with 'no-' to diables them, e.g. --no-proxy.

**Comment by darnir** [comment]
Yes, implementation of a `--no-proxy` switch is exactly what is required in this case. Like you said, the point of this switch would be to ignore any and all proxy settings that are set either using command line switches or environment variables.

This switch would cause `wget2` to not use any proxy at all.

**Comment by rockdaboot** [comment]
On we try to be backward compatible to wget 1.x (--no-proxy).
So for this issue, we just need to add --no-proxy for wget2 invocation in the test suite (simple change in one line). This might break some tests where we explicitly use --http_proxy=..., but that simply needs a preceeding --proxy to fix.

**Comment by rootkea** [comment]
I think I was looking for this.

    const char *executable="../../src/wget2_noinstall" EXEEXT " --no-proxy -d --max-threads=1 --prefer-family=ipv4";  

It does solved the hang problem. But still all tests fail except `test-parse-html`

Then I checked `test-suite.log` and it says `Unknown option 'proxy'`
Looks like `wget2` doesn't recognize `--proxy` option.

    $ wget2 --proxy
    Unknown option 'proxy'  

Confirms it.

Is `--proxy` option implemented? I need to look in code.

**Comment by rootkea** [comment]
Also we need to note that even after implementing `--proxy` option, above change won't solve the issue if `wget_test()` is called with `WGET_TEST_EXECUTABLE` option.

May be we should append `--no-proxy` after variable argument list gets processed? it's trivial to code. Waiting for your views.

**Comment by rockdaboot** [comment]
Lol, you are right - '--proxy' isn't implemented. Not sure why it appears in the --help list, must have started one day and then... :-)

**Comment by rootkea** [comment]
Oh yes. No entry for `proxy` in `options[]. I'm opening a new issue.

**Comment by rockdaboot** [comment]
> I'm opening a new issue.

Good !

**Comment by rockdaboot** [comment]
And forget about WGET_TEST_EXECUTABLE for now. I just needed it to test wget1.x with parts of the wget2 test suite. If we use it, that will be very controlled and we can add '--no-proxy' to the options when calling wget_test().
