### ISSUE TITLE
Implement --no-proxy to not use proxy even if proxy environment variables set

### ISSUE THREAD

**Issue by rootkea** [rockdaboot/wget2#149]
Also we need to implement  `--proxy` option to use proxy when proxy environment variables set. Should this be filed under separate issue?

**Comment by rockdaboot** [comment]
No. If you add --proxy as boolean, --no-proxy automatically works.

**Comment by rootkea** [comment]
Ok. So it's pretty evident that I need to solve this issue before #148

**Comment by rockdaboot** [comment]
:-) Yeah, pretty evident.

**Comment by rootkea** [comment]
Ok. I implemented environment proxy support and now I can fetch webpages using `wget2` command. I didn't use any option as using environment proxy is supposed to be default behavior. 

Now I need to check for `--proxy` and skip it i.e. do nothing.
I also need to check for `--no-proxy` and not processing the code I just added.

**Comment by rootkea** [comment]
Will update the code and then send a pull request.
