### ISSUE TITLE
A 302 redirect is considered to be a downloaded file

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#15]
Currently, a 302 redirect causes the URL to be added to the blacklist which is eventually used to count the number of files downloaded. As a result, Wget reports an extra *downloaded* file for each redirect encountered. This counter should be fixed.

**Comment by rockdaboot** [comment]
Technically, this is correct. Two downloads have been made, not matter what the user thinks what happened.
What we need is a 'stats' structure where we can put all those statistics that matter (# of requests, # of 200 OK, # of non-fatal errors, # of fatal errors, # number of redirects, # of errors, # bytes downloaded, etc). Especially for --spider mode this matters even more.

**Comment by darnir** [comment]
Technically, it is correct. But to a user who does not know anything about HTTP and simply attempts to download some files, the output looks incorrect. When we print something to screen, not in debug mode, the output has to be what the user expects to see, not what may nor may not be technically correct. 

I do like the idea of a stats structure that we can eventually print out to screen in some cases. I'm thinking aloud here now, but do you think its a sane idea to implement this in the library? I haven't thought much about how it would be done, but it may be a good idea for the struct to exist in the library such  that any client can access such data.

**Comment by rockdaboot** [comment]
What about partial downloads, e.g. one downloads 3 chunks/parts of a metalinked file with 100 parts in total. After that the file might be complete or not.
Or what do we say when using --continue(-download) ?
And we should distinguish between saved files and downloaded files.

**Comment by rockdaboot** [comment]
I pushed a commit to add some basic stats. This is just a starter, please feel free to extend it.
The output of downloaded files should now be correct (not sure what to do with --chunk-size).
