### ISSUE TITLE
Chunk size overflow

### ISSUE THREAD

**Issue by gvanem** [rockdaboot/wget2#153]
On this command `wget2 -d www.vg.no`, I'm getting a `Chunk size overflow #2: 8000`. And hence a short download. Not sure what's wrong, but Wget+curl have no problems with this URL (from a  *Apache/2.2.15 (CentOS)* server).

Note, the last `recvfrom()` returns 81761 bytes when this happens.

**Comment by rockdaboot** [comment]
Thanks for feedback. That is a change I made today for 32bit pointer wrap. I'll look at it tomorrow.

**Comment by rockdaboot** [comment]
Just tried it... can't reproduce (Debian amd64)

**Comment by rockdaboot** [comment]
Still can't reproduce on Alpine Linux x86. At least I found out that you need to `./configure --disable-zlib` to get a chunked Transfer-Encoding, where this king of message only can appear.

**Comment by gvanem** [comment]
It's true that with Zlib and `Accept-Encoding: gzip`, there is not problem with this host. 

But I rebuilt using gcc 5.1 (no Zlib, no libidn) and the problem was gone??
Must be something with the libraries I use for MSVC/clang-cl. Closing.

**Comment by rockdaboot** [comment]
Hmmm, i removed some code recently, that might have been wrong. I'll check again this weekend.

**Comment by rockdaboot** [comment]
Wrote a test to as reproducer. The problem is now fixed and we have a test to check chunked transfer-encoding now.
