### ISSUE TITLE
`./configure --enable-fsanitize-msan --enable-valgrind-tests && make check` completely freezes the system

### ISSUE THREAD

**Issue by rootkea** [rockdaboot/wget2#165]
`./configure --enable-fsanitize-msan --enable-valgrind-tests && make check` dooms the system. I didn't test but I think `./configure --enable-fsanitize-asan --enable-valgrind-tests` does the same.

We should:

1. Fail `./configure` when we see `asan/msan` and `valgrind`, spitting out the message of they being mutually exclusive instead of allowing it and then making the developer crying out blaming valgrind ;)
2. Most importantly *mention* this in `./configure --help`
I'm amazed `./configure --help` says nothing about even `asan` and `msan` being mutually exclusive. It's only when dev tries the actual command they find out this *after* the `./configure` fails!

**Comment by akashrawal** [comment]
I see, valgrind is allocating all memory and stops responding to interrupts. It's likely valgrind bug or just that added instrumentation requires even more memory on valgrind's side (the latter is not explaining why valgrind is not responding to interrupts.)

For now you could use [magic sysrq](https://fedoraproject.org/wiki/QA/Sysrq) or just kill valgrind just before allocating all memory.

**Comment by rootkea** [comment]
Yes. A bit busy busy with college stuff right now. Semester is about to end!
I'll look into this later. Maybe tomorrow.

**Comment by darnir** [comment]
It's because of the instrumentation code. Compiler added instrumentation will interfere with valgrind causing a lot of trouble. As I indicated earlier, you should use either of valgrind or instrumentation but not both together.

We would indeed improve the help output in configure to mention that these are mutually exclusive options. However, remember that a developer can simply pass `TESTS_ENVIRONMENT="VALGRIND_TESTS=1"` to `make check` and work around the restriction in the configure stage. Hence, the best way to deal with this is actually educating all the developers about the pitfalls.

**Comment by rootkea** [comment]
Ok. So I propose 2 things:

1. `./configure --help` should document about `asan` and `msan` being mutually exclusive. Currently `./configure` fails if both `asan` and `msan` are passed and prints the message about their mutual exclusiveness *after* the command has been tried.
2. Now about memory sanitizers and valgrind.  
Yes. A user(dev) can bypass the check in `configure.ac` using `TESTS_ENVIRONMENT="VALGRIND_TESTS=1" make check` but same can be done with `asan` and `msan` as `CFLAGS=-fsanitize=address ./configure --enable-fsanitize-msan` and *still* there is a check for their mutual exclusiveness in `configure.ac`. Sure. We can't stop somebody who are keen to shoot in their foot but we can at least set checks in place. :)
So for point no. 2 I propose that
a. we place a check similar to `asan` and `msan` check in `configure.ac` for memory sanitizers and Valgrind being together.
b.Let `./configure --help` document about this.

What do you guys think?

**Comment by rockdaboot** [comment]
I am fine with 1. and 2.

**Comment by rootkea** [comment]
I added the test for sanitizers and Valgrind being together and it works as expected. But I am not able to figure out where to put the help text. Can anybody please guide me about how this text `Use these variables to override the choices made by 'configure' or to help it to find libraries and programs with nonstandard names/locations.` from `configure --help` got there?
