### ISSUE TITLE
wget_hpkp_set_maxage() prototype

### ISSUE THREAD

**Issue by gvanem** [rockdaboot/wget2#166]
Not sure how this happened, but now:
```
libwget/hpkp.c(180,6):  error: conflicting types for 'wget_hpkp_set_maxage'
void wget_hpkp_set_maxage(wget_hpkp_t *hpkp, time_t maxage)
     ^
./include/wget\wget.h(1059,2):  note: previous declaration is here
        wget_hpkp_set_maxage(wget_hpkp_t *hpkp, long maxage);
        ^
```
`time_t` != `long` on many platforms (including Windows).

**Comment by rockdaboot** [comment]
Thanks, that is my (recent) fault. Neither my machine nor the CIs (including OSX) mourned... (sigh)

**Comment by gvanem** [comment]
AppVeyor anyone?

**Comment by rockdaboot** [comment]
see #61

**Comment by rockdaboot** [comment]
@rootkea How to auto-close an issue with a PR: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by rootkea** [comment]
Sorry forgot!

**Comment by rockdaboot** [comment]
No problem, I forget it myself almost all the time. Just wanted to mention it, in case you didn't know.
