### ISSUE TITLE
futimens() on Win32

### ISSUE THREAD

**Issue by gvanem** [rockdaboot/wget2#167]
Seems there is some troubles in Gnulib's `futimens()` because after a download, I always get:
```
Failed to set file date: Function not implemented
HTTP response 200 OK
```
But setting a file-time could be done using Windows' native `SetFileTime()` function.  

*Edit:* Or change `set_file_mtime() ` to take a file-name too and simply use `utime()`?

**Comment by rockdaboot** [comment]
I have this as well when building with MinGW.
It would be nice to see this in gnulib... I'll check it out.

**Comment by rockdaboot** [comment]
My patch works with MinGW, please check on real Windows...

**Comment by gvanem** [comment]
Works fine.

**Comment by gvanem** [comment]
Works. Except when the output is `-O NUL`. Then I get a `Failed to set file date: No error`. Should one call `futimes()` then? Would be nice to get an error-text in any case.

**Comment by rockdaboot** [comment]
'No error' is interesting. Mayby we should not print an error message for 'no error' !?
AFAIK, NUL is the Windows pendant to Linux' /dev/null. I'll check the behaviour with /dev/null tomorrow...

**Comment by rockdaboot** [comment]
Linux with `-O /dev/null`: `Failed to set file date: Operation not permitted`.
As you say, we could skip futimens() for NUL on Windows and /dev/null on anything else.
