### ISSUE TITLE
cut-dirs is broken

### ISSUE THREAD

**Issue by 5hd** [rockdaboot/wget2#170]
As I understand it, currently the "cut-dirs" setting is broken.
Issues I encountered:
+ --cut-dirs=1 together with --no-host-directories will fail to save any file
+ leading / should be removed

See my commit here: https://github.com/MichaelHeerklotz/wget2/commit/fb665a12d3d1b8a1d4154847ed5f1350741fd8bf

**Comment by rockdaboot** [comment]
(Sorry if you get this twice (also put as comment to your commit))

Thanks for having a look at it.
Please create a pull request (PR) - then your changes are automatically checked by our Continuous Integration (Travis CI). If that passes, I'll do a manual review.

If you have time and joy, please add a test case to reproduce a/the problem (see tests/test.*.c as examples).

**Comment by MichaelHeerklotz** [comment]
Okay, I will give it a try in a few days, if I find the time.

**Comment by rockdaboot** [comment]
Fixed by #185
