### ISSUE TITLE
`./configure` falsely claims that compiler doesn't support -fsanitize=thread

### ISSUE THREAD

**Issue by rootkea** [rockdaboot/wget2#171]
$ gcc --version
    gcc (Debian 4.9.2-10) 4.9.2

    $ ./configure --enable-fsanitize-tsan
    ...
    checking whether C compiler handles -fsanitize=thread... no
    ...

CFLAGS from ./configure output doesn't include `-fsanitize=thread`

But gcc 4.9.2 manual says it does support `-fsanitize=thread`

**Comment by rootkea** [comment]
Ok. So I tried `CFLAGS="-g -fsanitize=thread" ./configure` instead but ./configure still failed.
Here is the relevant log from `config.log`:

    gcc version 4.9.2 (Debian 4.9.2-10) 
    configure:4744: $? = 0
    configure:4733: gcc -V >&5
    gcc: error: unrecognized command line option '-V'
    gcc: fatal error: no input files
    compilation terminated.
    configure:4744: $? = 4
    configure:4733: gcc -qversion >&5
    gcc: error: unrecognized command line option '-qversion'
    gcc: fatal error: no input files
    compilation terminated.
    configure:4744: $? = 4
    configure:4764: checking whether the C compiler works
    configure:4786: gcc -g -fsanitize=thread   conftest.c  >&5
    gcc: error: -fsanitize=thread linking must be done with -pie or -shared
    configure:4790: $? = 1
    configure:4828: result: no

**Comment by rootkea** [comment]
So to fix this issue, when `--enable-fsanitize-tsan` is passed to `./configure` we should:

1. Detect correctly that the compiler supports `-fsanitize=thread`
2. If gcc 4.9 (I have no idea about other compilers/versions) add `-fsanitize=thread -fPIC -pie` to CFLAGS.

**Comment by darnir** [comment]
I think you can simply add the `-fPIC -pie` flags to the thread sanitizer in all cases. Those flags will cause the compiler to create a "Position Independent Executable" which is better from a security standpoint anyways.

**Comment by rockdaboot** [comment]
Thanks for working on this (Fixed by #176).
