### ISSUE TITLE
Combining Memory and Thread sanitizers fails almost all of the tests

### ISSUE THREAD

**Issue by rootkea** [rockdaboot/wget2#173]
Since currently `./configure` can't recognize compiler being supporting `-fsanitize=thread`( #171) I used following command:

    $ CFLAGS="-g -fsanitize=thread -fPIC -pie" ./configure --enable-fsanitize-msan
This fails 29 of 31 tests. Here are few logs[0][1]

I think this is happening because `tsan` and `msan` aren't compatible and should be used in a mutually exclusive manner exactly like `asan` and `msan`.

If that's the case indeed  then we need to have a check for `tsan` and `msan` in `./configure` exactly like the existing check for `asan` and `msan`

[0] test-metalink.log: https://pastebin.com/zY5qKsU8
[1] test-parse-css.log: https://pastebin.com/mQXVYzfM

**Comment by darnir** [comment]
Yes, far as I'm aware, the memory sanitizer cannot be used in conjunction with anything else. In fact, only `ubsan` can (should) be combined with any other sanitizers.

**Comment by rootkea** [comment]
@darnir Ok. Thanks. I'll send the PR adding a check in `configure.ac`
