### ISSUE TITLE
Prevent certain combination of flags

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#180]
In wget1.x we have a extended logic to check if the given option combine or not.
In Wget2 we didn't implement this yet.
E.g. allowing `--chunk-size=x` and `-O -`... with max-threads>1 the chunks won't be downloaded in order, so output to a non-seekable file/device will certainly result in garbage.
Maybe it is a good time to transfer the logic from wget1.x to wget2 and also think about combinations of the new wget2 options.

**Comment by darnir** [comment]
In Wget1.x we use a very naive technique to implement this. A large set of `if() .. else` conditions. It is also the simplest and most obvious way to approach the problem. I agree, that we should start looking into mutually exclusive combinations and preventing them.

However, for the specific example you cite, in such a case, we should identify if the underlying filesystem allows random seeks and writes and disable the combination *only* if it doesn't. Similarly, it should also disable metalink support with multiple threads.
