### ISSUE TITLE
Should we use C99 bit-width defined integers ?

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#181]
In the past we had several issues when assuming certain bit-widths for integer types.
IMO, since we are C99, we should make use of (u)intX_t from stdint.h in some situations.
E.g. using int64_t instead of 'long', 'long long' or even 'off_t'.

Is there any caveat ?

**Comment by darnir** [comment]
I don't see any blocking issues to this change. We should indeed switch to C99 fixed width integers. It will make our life much simpler.

**Comment by rockdaboot** [comment]
Let's do that step by step (whenever appropriate). E.g. the bar code needs int64_t instead of off_t !?
