### ISSUE TITLE
--chunk-size with existing file inhibts download

### ISSUE THREAD

**Issue by rootkea** [rockdaboot/wget2#182]
If there is an existing file with the same name as the one we want to download then both `wget` and `wget2` overwrite that file. This is an expected behavior.

We have `-c` switch if user wants to continue download from where they left out.

But when I use `--chunk-size` with already existing file, download doesn't start.

    $ ls
    $ touch 10Mb.dat
    $ wget2 --chunk-size=1k -O 10Mb.dat http://ovh.net/files/10Mb.dat
    [0] Checking 'http://ovh.net/files/10Mb.dat' ...
    HTTP response 200 OK
    Failed to build checksum, assuming file to be OK
Is this an intended behavior? I expected file to get downloaded overwriting the existing one since there is no `-c` on command line.

**Comment by darnir** [comment]
No. This is indeed a bug and not intended behaviour. My guess it that it occurs because of the fact that chunk-size downloads are currently implemented as an edge case of metalink. The "Failed to build checksum ..." output seems to validate this hypothesis.

Since this and similar cases could occur in the future, would you mind adding a new test case to the tests for this combination of options? After that we can look into adding another check somewhere to ensure clobbering / continuing of the file.

**Comment by darnir** [comment]
Also, the `-O 10Mb.dat` switch isn't required to trigger the bug. And I can confirm that downloading the file fails even with the `-c` switch. This is most definitely a side effect of metalink

**Comment by rockdaboot** [comment]
Are you on latest master ? I thought I fixed the bug today ...

**Comment by rockdaboot** [comment]
As @darnir says, it is a side effect. Metalink has checksums for each chunk, so it knows (tests) for integrity and then only downloads the incomplete/missing chunks. So metalink doesn't need a -c, it does automatically the right thing (well, sort of). For --chunk-size this behavior must be slightly changed.

**Comment by rockdaboot** [comment]
I pushed a branch 'chunk-size' with a fix for partially existing files. Now --chunk-size works as if -c was given. Not sure if that is what we want...

There is another bug (regression): The metalink parts / chunks are only downloaded by one single thread. That is unexpected behavior.

**Comment by rootkea** [comment]
> Now --chunk-size works as if -c was given.

We should overwrite the existing file unless a `-c` is passed explicitly IMO. That's what `wget` does and users will expect the same behavior.

**Comment by rockdaboot** [comment]
> We should overwrite the existing file unless a -c is passed explicitly IMO. That's what wget does (when no -c is present) and users will expect the same behavior.

Sounds right !

**Comment by rootkea** [comment]
I could work on this and the proxy issue right now but my exams are going on. So can't invest much of a time. Nevertheless I do manage to find time to check up on project progress :)
