### ISSUE TITLE
page-requisites not working as intended

### ISSUE THREAD

**Issue by MichaelHeerklotz** [rockdaboot/wget2#183]
The page-requisites setting (the code around "link_inline") is not working as (probably) intended at the moment. I guess someone tried to fix it, and broke it instead.

The comment for "link_inline" says:
link_inline : 1; // 1 = rel was 'stylesheet' or 'shortcut icon'

But we are skipping files with link_inline == 1 with the "|| html_url->link_inline" check (see bottom).

So I guess:
`if (!wget_strncasecmp_ascii(val, "icon shortcut", len) || wget_strncasecmp_ascii(val, "stylesheet", len))`
should be:
`if (!wget_strncasecmp_ascii(val, "icon shortcut", len) || !wget_strncasecmp_ascii(val, "stylesheet", len))`

and 
`|| html_url->link_inline`
should be:
`|| !html_url->link_inline`

Then it would make sense again, but would still be broken, because aside from not clearing "link_inline" back to 0 when the link tag closes, it would work for
`<link  rel="stylesheet"  href="test.css" />`
but not for
`<link href="test.css" rel="stylesheet" />`
because in the second case we get the "rel" value after the "href" value and the link as already been added to the list with  "link_inline"  == 0.

I see two solutions here:

A. Just download all "link" href values when page-requisites is enabled, ignoring the "rel" value (easy fix).
B. Only download the link href when rel is "icon shortcut" or "stylesheet" (hard fix, we would need to cache the href/rel values of the link tag).

I do not see a big problem with downloading a bit too much (A), so I would fix it with solution A until someone has the time for B.

Do you agree?

```
		// with --page-requisites: just load inline URLs from the deepest level documents
		if (page_requisites && !wget_strcasecmp_ascii(html_url->attr, "href")) {
			// don't load from dir 'A', 'AREA' and 'EMBED'
			// only load from dir 'LINK' when rel was 'icon shortcut' or 'stylesheet'
			if ((c_tolower(*html_url->dir) == 'a'
				&& (html_url->dir[1] == 0 || !wget_strcasecmp_ascii(html_url->dir,"area")))
				|| html_url->link_inline
				|| !wget_strcasecmp_ascii(html_url->dir,"embed"))
			{
				info_printf(_("URL '%.*s' not followed (page requisites + level)\n"), (int)url->len, url->p);
				continue;
			}
		}
```
		
		
```
		if ((*tag|0x20) == 'l' && !wget_strcasecmp_ascii(tag, "link")) {
			if (!wget_strcasecmp_ascii(attr, "rel")) {
				if (!wget_strncasecmp_ascii(val, "icon shortcut", len) || wget_strncasecmp_ascii(val, "stylesheet", len))
					ctx->link_inline = 1;
				else
					ctx->link_inline = 0;
			}
		}
```

**Comment by MichaelHeerklotz** [comment]
Also, to load css asynchronously, rel=preload is used, together with some JavaScript to change rel to stylesheet after loading, so loading all links would take care of this case,too

**Comment by rockdaboot** [comment]
Very good analysis !

>  I guess someone tried to fix it, and broke it instead.

Oh oh, that was me. That was new code and I admit I just tested it with "icon shortcut". Not even made up a test code for it (slap myself).

> I do not see a big problem with downloading a bit too much (A)

That is how it was. My intention was to have a behavior comparable to Wget1.x.

So yes, please go ahead with (A). In the meantime, I'll create a new branch with test cases that would help us with (B).

**Comment by rockdaboot** [comment]
IMO, with --page-requisites:
* `<link rel="shortcut icon" href="myfavicon.ico" />` should be followed
* `<link rel="stylesheet" href="test1.css" />` should be followed
* `<link href="test2.css" rel="stylesheet" />` should be followed
* `<link href="page/url" rel="whatever" />` should **not** be followed

I just pushed an amended `test--page-requisites.c` to cover these cases and used that to fix regarding (B). Another problem was "icon shortcut" instead of "shortcut icon" ;-)

Works as old Wget1.x now.

**Comment by rockdaboot** [comment]
> Also, to load css asynchronously, rel=preload is used, together with some JavaScript to change rel to stylesheet after loading, so loading all links would take care of this case,too

Pushed a change so that rel=preload is followed on --page-requisites.
If you have time, please review / comment.

**Comment by MichaelHeerklotz** [comment]
Good work! I think everything works perfectly now.
