### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by tholu** [rockdaboot/wget2#198]
Is there a homebrew formula for wget2 somewhere? Is it planned to publish one?

**Comment by rockdaboot** [comment]
Hi Thomas,

no there is no homebrew formula yet. And there currently is no one working at wget2 with the relevant knowledge. The wget2 dev takes place at https://gitlab.com/gnuwget/wget2.

It would be great if someone (maybe you !?) could work on it. If there is anything that we can do upstream, let us know.

**Comment by tholu** [comment]
Thanks for the fast answer, I'll try to create one and will share what happens.
