### ISSUE TITLE
Failed to connect: Wget has been built without TLS support

### ISSUE THREAD

**Issue by tinygipxy** [rockdaboot/wget2#201]
I got this error when trying download from https url, kindly help on how to compile with https enable ?

**Comment by rootkea** [comment]
Does your setup fulfill build requirements specified in [README](https://gitlab.com/gnuwget/wget2/blob/master/README.md)?  
More specifically do you have `libgnutls` installed?  

Also, this is just a mirror. Official `wget2` repo is at https://gitlab.com/gnuwget/wget2 Please open issue(s)/submit merge request(s) there. :)

**Comment by rockdaboot** [comment]
Thanks @rootkea. Especially you need GnuTLS development files, e.g. on a recent Debian/Ubuntu `apt-get install gnutls-dev`.

**Comment by tinygipxy** [comment]
I'm on centos 7, so "yum install gnutls-devel", then can downoad from https now, thank you

**Comment by JustCodin** [comment]
I followed the solution above and fixed it with "sudo yum -y install gnutls-devel" and confirmed this by running `./configure` and checking `SSL/TLS support:    yes`, and then rebuilt it and tried to use wget again `wget [url]`, but then ran into:
```
TLS False Start requested but Wget built with insufficient GnuTLS version
WARNING: OCSP is not available in this version of GnuTLS.
ERROR: The certificate is not trusted.
ERROR: The certificate doesn't have a known issuer.

Failed to connect: Certificate error
```

But when I try to install/update `gnutls`, I'm informed:
`Package gnutls-2.12.23-21.18.amzn1.x86_64 already installed and latest version`
so I'm not sure how to proceed as it shows the most up to date package.

Thanks in advance for any help you can provide.

**Comment by rockdaboot** [comment]
Looks pretty good to me - you are just tiny little step behind. Your wget2 has TLS support, else you wouldn't see those messages.

TLS False Start is absolutely not needed for functionality. It gives you just a little speed gain during TLS connection phase, by 1 RTT (that's ~ ping time to the server).

OCSP gives you more security. It checks that the server certificate hasn't been revoked. Not doing this check doesn't impair functionality.

The errors mostly say that you didn't install the CA certificate(s) needed to check the server certificate. Here on Debian you have to install a package named 'ca-certificates'. Not sure what it's named on CentOS 7. You *need* this to stay *secure* and avoid man-in-the-middle (MITM) attacks.

As a desperate fallback, you can switch off the security checks with `--no-check-certificate`. Please try to avoid it !

**Comment by JustCodin** [comment]
@rockdaboot Thanks for the clear and informative explanation. In attempting your solution, I ran into an issue.

When I run `sudo yum install -y ca-certificates` it outputs:
```
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main                                                | 2.1 kB     00:00     
amzn-updates                                             | 2.5 kB     00:00     
Package ca-certificates-2017.2.14-65.0.1.17.amzn1.noarch already installed and latest version
Nothing to do
```

So it seems that the required certificates are already installed. It's good to know that `--no-check-certificate` exists in a worst-case-scenario, but I'm hoping to not have to use it. 

Do you have any how to troubleshoot further?

**Comment by rockdaboot** [comment]
@JustCodin Maybe that (really old) version of GnuTLS doesn't find the directory with the CA certificates. Another possibility is that your CA certificates doesn't contain the needed one (some websites tell you where to download the certificate incl. instructions how to install it).

But let's assume that it's first problem. How to check that is calling `wget2 -d https://www.example.com`. The debug output gives you a lot of hints, like
```
21.211020.785 GnuTLS init                                                                                               
21.211020.799 Certificates loaded: 128                                                                                  
21.211020.799 GnuTLS init done                                                                                          
```
If you see `Certificates loaded: 0`, then GnuTLS doesn't find your CA directory. Here, it is `/etc/ssl/certs/`. Maybe you can list the contents of package `ca-certificates` to see where the cert files are stored. Sometimes they are all concatenated into one .pem or .crt file like `ca-certificates.crt`.

Wget/Wget2 have `--ca-directory=<dir>` to specify that directory. Use again -d to see how many certs have been loaded.

**Comment by JustCodin** [comment]
@rockdaboot You were correct that GnuTLS couldn't find the CA directory and your trouble shooting proved most effective. The CA directory that worked on my machine was `/etc/pki/ca-trust/extracted/pem/`. When I pass it to the wget2 command suing `--ca-directory=<dir>`, it worked! But when I passed the `-H` option, too, the command initially runs, but then aborts after a few moments and returns the following error: 
```
Ohhhh jeeee: Assertion `pool_is_locked' failed (random-csprng.c:1078:add_randomness)
Aborted
```
The only reference I could find to this error was on a separate package, but similar issue with TLS [here](https://github.com/rsyslog/rsyslog/issues/1615#issuecomment-364780722), and the following [comment](https://github.com/rsyslog/rsyslog/issues/1615#issuecomment-423099535) mentioned a potential issue. Does this imply that it's ultimately an issue with gnuTLS and the OS?

Thanks, again, for all your help.

**Comment by rockdaboot** [comment]
That seems to be a multi-threading issue, but I can't even say where exactly. Your links say it's GnuTLS, but there is no such 'Ohhhh jeeee' string, nor a function called 'add_randomness', nor 'pool_is_locked'.

Anyways, it seems to be fixed since long time. But 'stable' OSes very seldom backport fixed bugs - which makes them in fact much more 'unstable' and more vulnerable to attacks. While the up-to-date systems have thousands of thousands of bugs fixed, the 'stable' don't do (or sometimes, when there is a CVE tracking number, which often isn't).

Anyways, here are two options you can try:

- reduce multi-threading to one worker thread by using --max-threads=1. Of course your this will reduce download speed dramatically for recursive downloads.

- update to a newer OS

- build and install GnuTLS and it's dependencies. You would install them locally, e.g. in your home directory. We do this for MinGW (and others) and have a script `contrib/mingw`. Amend it to your environment - shouldn't be too much work. And you'll end up with a new level of freedom :-)

**Comment by Waffa** [comment]
I got the same issue now on: 

`eesti@eesti-ThinkPad-T420:~/Documents/bioweapon/jamesjmurray.blog$ wget2 --mirror -p --html-extension --convert-links -e robots=off -P . https://jamesjmurray.blog/2017/01/11/a-psychedelic-silver-lining-2/
Failed to connect: libwget has been built without TLS support
Segmentation fault (core dumped)
`

**Comment by rockdaboot** [comment]
@Waffa Please read the above thread - it should solve your issue. Of course the segfault should not be, will take a look.

**Comment by rockdaboot** [comment]
@Waffa Segfault fixed
