### ISSUE TITLE
Poor error information upon download errors, uncertain what action to take

### ISSUE THREAD

**Issue by themaverick** [rockdaboot/wget2#214]
Hello! As I am downloading a large amount of data (still ongoing), I ran into these errors using this wget2 command below on Debian below. Other than these errors, the "Total Errors: 24" - is that representative of these errors down below? 

The lack of information from errors makes me unsure of the integrity and availability of my downloads.

`wget2 --max-threads=30 -e robots=off -r -np --fsync-policy on --tls-resume on --retry-connrefused --level 15 --tries 30 <URL> --progress bar`

**Why is this a issue?**
I am not certain as to whether or not:

1. Files have been corrupted and need to be re-downloaded
2. Which files were affected/URL of file affected
3. The time that it occurred at
4. The URL the error occurred when attempting to resolve. 
5. How do I know if these multiple attempts eventually made it and the file is successfully written to disk, and therefor do not have to worry about it? 

Please let me know if there is some additional information otherwise that I am missing, any help would be appreciated.

Thank you to the awesome devs who made this. You guys `wget` it. 

````
Failed to resolve on (Name or service not known)
Failed to resolve on (Name or service not known)
Failed to resolve on (Name or service not known)
Just got 3108384 of 152035835 bytes
Just got 180304 of 2853691444 bytes
Just got 20925224 of 49385236 bytes
Just got 32699808 of 516460626 bytes
Just got 7042016 of 1073741824 bytes
Just got 412736 of 2147483648 bytes
Just got 7135856 of 21479915 bytes
Just got 438800 of 1575784415 bytes
Just got 185004 of 3221225472 bytes
Just got 103916 of 2147483648 bytes
Just got 1108 of 2147483648 bytes
Just got 280968 of 2147483648 bytes
Just got 1108 of 2147483648 bytes
Just got 289656 of 2147483648 bytes
Just got 1109 of 1454191499 bytes
Just got 1108 of 1073741824 bytes

Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to read 102400 bytes (104)
Failed to resolve on (Name or service not known)
Failed to resolve on (Name or service not known)
Failed to resolve on (Name or service not known)
Failed to resolve on (Name or service not known)
Failed to resolve on (Name or service not known)

Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to resolve on (Name or service not known)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to write 327 bytes (32)
Failed to resolve on (Name or service not known)
Just got 2706636800 of 4294967296 bytes
Just got 2172836096 of 3221225472 bytes
Just got 2246167912 of 3221225472 bytes
Failed to resolve on (Name or service not known)
Failed to resolve on (Name or service not known)
```

**Comment by rockdaboot** [comment]
Hm, boolean options need no 'on'. E.g. just use `--fsync-policy --tls-resume` or alternatively use `--fsync-policy=on --tls-resume=on`.

**Comment by rockdaboot** [comment]
In your command line 'on' are URLs. So you see errors like "Failed to resolve on ...". Maybe it helps if this would be "Failed to resolve 'on' ..." !?
I agree that "Failed to write" and "Just got" messages could have a bit more information ;-)

**Comment by themaverick** [comment]
> 
> 
> In your command line 'on' are URLs. So you see errors like "Failed to resolve on ...". Maybe it helps if this would be "Failed to resolve 'on' ..." !?
> I agree that "Failed to write" and "Just got" messages could have a bit more information ;-)

Thank you for your replies @rockdaboot ! So for the failed to write messages that repeat, does that mean that those files are now corrupted or eventually after the error stopped repeating it had been successfully written, or otherwise? I am concerned I have to re-download items and I do not know which files were corrupted.

**Comment by rockdaboot** [comment]
I am unsure here without testing myself. It could be literally anything. Maybe -d gives you more information. Try with single files first to see if that messge is always exactly the same. -d should also tell you which side is hanging up.

Are you sure that you have the latest wget2 from master ?

**Comment by rockdaboot** [comment]
> So for the failed to write messages that repeat, does that mean that those files are now corrupted or eventually after the error stopped repeating it had been successfully written, or otherwise?

This error messages mean that wget2 failed to send the request to the server, likely due to a failed connect or dropped connection. I just changed the message from 'Failed to write' into 'Failed to send', so it's a bit clearer what happened.

If you think there are more issues that I didn't address, please open a new issue.
