### ISSUE TITLE
Ctrl + C ignored

### ISSUE THREAD

**Issue by coinhubs** [rockdaboot/wget2#215]
Hello

Often Ctrl +C is ignored. Could it be handled please?

$ time wget2 -O test.txt mymissingweb123.com
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
^CFailed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
^C^CAborted

real	1m13.394s
user	0m0.009s
sys	0m0.016s

wget2 --version
GNU Wget2 1.99.1 - multithreaded metalink/file/website downloader

**Comment by rockdaboot** [comment]
That's on purpose.
The first CTRL-C is a 'soft stop' to give all worker threads time to finish what they are doing and to stop smoothly.
The second one is then the 'hard stop' if you have to wait too long.
