### ISSUE TITLE
no default timeout

### ISSUE THREAD

**Issue by coinhubs** [rockdaboot/wget2#216]
Hello
I noticed there aren't any timeouts, on attempts or time based...
could something sensible be added... maybe 30 seconds or 3 DNS errors?

$ time wget2 -O test.txt mymissingweb123.com
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
^CFailed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
Failed to resolve mymissingweb123.com (Name or service not known)
^C^CAborted

real	1m13.394s
user	0m0.009s
sys	0m0.016s

wget2 --version
GNU Wget2 1.99.1 - multithreaded metalink/file/website downloader

**Comment by rockdaboot** [comment]
The defaults ar the same as for Wget 1.x and are pretty long. The default retry setting is 20, AFAIR. 
You can set your own default values in a config file that is automatically read (see `--config-file` in wget2.md).

**Comment by coinhubs** [comment]
OK i see.
