### ISSUE TITLE
--version prevents normal operation

### ISSUE THREAD

**Issue by coinhubs** [rockdaboot/wget2#219]
Hello
could --version also allow normal operation please?
Currently it exits, I had expected to be able to see the version as it was downloading 

$ wget2 --version  http://www.google.de
GNU Wget2 1.99.1 - multithreaded metalink/file/website downloader

+digest +https +ssl/gnutls +ipv6 +iri +large-file +nls -ntlm -opie +psl +iconv +idn2 +zlib +lzma +brotlidec +bzip2 +http2 +gpgme

**Comment by rockdaboot** [comment]
We won't "fix" this. The current behavior is the same as with most *nix tools out there.
E.g. try
```
touch x
rm --version x
```
You'll see the version output and `x` won't be removed.
