### ISSUE TITLE
wget2 -o mylog.log --version  logging still on stdout

### ISSUE THREAD

**Issue by coinhubs** [rockdaboot/wget2#221]
$ wget2 -o mylog.log --version
GNU Wget2 1.99.1 - multithreaded metalink/file/website downloader

+digest +https +ssl/gnutls +ipv6 +iri +large-file +nls -ntlm -opie +psl +iconv +idn2 +zlib +lzma +brotlidec +bzip2 +http2 +gpgme

**Comment by rockdaboot** [comment]
Yes, that is compatibility to other GNU tools (e.g. try wget).
So if you want the output to go into mylog.log, use `wget --version >mylog.log`.
