### ISSUE TITLE
Fix potential race condition in HSTS

### ISSUE THREAD

**Issue by juaristi** [rockdaboot/wget2#23]
Same as [f5a63e31006ed02f5de4bb8d947bc7b755bb81fe](http://git.savannah.gnu.org/cgit/wget.git/commit/?id=f5a63e31006ed02f5de4bb8d947bc7b755bb81fe) in wget.

I have seen no file locking in the HSTS code. While it's true it creates some (one?) mutexes, they seem to be for internal threads synchronization only (i.e. to make the HSTS API thread-safe).

Although I haven't had time to prove this yet, it looks like other wget2 processes might clobber the HSTS file.

**Comment by rockdaboot** [comment]
Absolutely right. It misses the code that you already built into Wget1 after GSOC.
Please add the locking code (and maybe something else I missed) to Wget2.

**Comment by rockdaboot** [comment]
Fixed by #37
