### ISSUE TITLE
How install on windows?

### ISSUE THREAD

**Issue by shadowzoom** [rockdaboot/wget2#233]

**Comment by bopoh13** [comment]
Use `curl` on win10

**Comment by rockdaboot** [comment]
We do not provide executables, just source code.
The source code can be cross-compiled into Windows executables (we do this as part of the CI testing).

But from your question I conclude that building from source is no option for you.
So you have to ask the search machines for help - I now people are already using Wget2 on Windows.
For single file downloads `curl` is indeed a good alternative, but it's not made for complex tasks such as recursive downloading web sites.
