### ISSUE TITLE
"Failed to parse date"

### ISSUE THREAD

**Issue by gvanem** [rockdaboot/wget2#237]
When doing a `wget2 -d https://www.cnn.com`, I do get an `index.html` page.
But also this message:
```
Failed to parse date 'Sat Jul 01 2023 00:00:00 GMT; SameSite=Lax'
```

Since it's in the future?
I'm on Windows-10 with a clang-cl built Wget2 from master.

**Comment by rockdaboot** [comment]
Hey, we support currently these formats:
- RFC 822 / 1123: Wed, 09 Jun 2021 10:18:14 GMT
- RFC 850 / 1036 or Netscape: Wednesday, 09-Jun-21 10:18:14 or Wed, 09-Jun-2021 10:18:14
- ANSI C's asctime(): Wed Jun 09 10:18:14 2021

'Sat Jul 01 2023 00:00:00 GMT' looks a bit like a bit from everything. What format is that ?

**Comment by rockdaboot** [comment]
https://tools.ietf.org/html/rfc7231#section-7.1.1.1
