### ISSUE TITLE
Download unresponsive in the middle.

### ISSUE THREAD

**Issue by junomarian** [rockdaboot/wget2#239]
Hey Dev, The downloads stops is the middle. No data being download. But the same link opens in Browser. There is no error. no pause or stop. Just no data transfer.
Had to cancel and run command again. then it works.
urls.txt contains direct image links. 500 links. 1-2 mb each. 
 
I generally use these commands 
$ wget2 -i urls.txt 
$ for f in *.txt;do wget2 -i "$f" -P "$f";done

How i can resolve that download stop in the middle? Is there any way to skip that file which is giving problem and jump to next?
Thanks
My bad English.

**Comment by rockdaboot** [comment]
Hey @junomarian,

my guess is that the default values for timeout and number of retries should be changes. Else you can run into a seemingly stalled wget2.
So possibly use `--tries=1 --timeout=30`, that means "only try once" and "max. wait 30s".

Of course there could be one or more files being downloaded very slow. Just think of 1 byte per second and the file is 1MB in size :laughing:
