### ISSUE TITLE
Option --config-file should be renamed to --config (backwards compatibility)

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#24]

**Comment by darnir** [comment]
Oh. I thought it was called `--config-file`. Didn't actually check though. However, are we really going for completely backward compatibility? I thought one of the reasons for Wget2 was so that we could break a few things in Wget.

And since all the other options are named as `--xxx-file`, I guess naming it as `--config-file` is more intuitive and easier to remember.

**Comment by rockdaboot** [comment]
What about having a 'hidden' --config option ?

**Comment by darnir** [comment]
I'm not sure adding that kind of complexity in the code is a good idea. Do we want Wget2 to definitely be a full drop in replacement for Wget? 

Because then we have quite a few problems to resolve. Else, I vote for simplicity.

**Comment by rockdaboot** [comment]
It is just one single line:
```
diff --git a/src/options.c b/src/options.c
index 6a57aa1..b642d39 100644
--- a/src/options.c
+++ b/src/options.c
@@ -633,6 +633,7 @@ static const struct option options[] = {
        { "check-hostname", &config.check_hostname, parse_bool, 0, 0 },
        { "chunk-size", &config.chunk_size, parse_numbytes, 1, 0 },
        { "clobber", &config.clobber, parse_bool, 0, 0 },
+       { "config", &config.config_file, parse_string, 1, 0}, // for backward compatibility only
        { "config-file", &config.config_file, parse_string, 1, 0},
        { "connect-timeout", &config.connect_timeout, parse_timeout, 1, 0 },
        { "content-disposition", &config.content_disposition, parse_bool, 0, 0 },
```

**Comment by rockdaboot** [comment]
If we document the difference regarding --config/--config-file, it is more complex than just adding the option silently.

**Comment by darnir** [comment]
I know that it is just one single line.. For now..
What I'm trying to prevent is people coming up later and saying, "You provided compatibility for --config, do it for XXX also"

So long as we agree on not doing this for all options where Wget and Wget2 differ, I'm okay. Else, we will definitely have a huge set of options even hidden ones that we need to support.

**Comment by rockdaboot** [comment]
There is a list of options that differ between Wget and Wget2.
We should make this complete (or check if it is complete) and add comments.
(E.g. I made a comment to --egd-file today.)
If we have it completed, we can easily see how much work it will be to stay backward compatible.
IMO, if it doesn't hurt, let's try to stay close to Wget.

**Comment by rockdaboot** [comment]
Let's do it in a reasonable way. We don't have to support $WGETRC (people should use --config/--config-file) or $SYS_WGETRC (we might need this as ./configure option).

Options that Wget1 has but Wget2 not should be implemented sooner or later, except very weird ones. We can decide this from case to case when it comes to that point.
