### ISSUE TITLE
Feature Request: Prevent empty directories

### ISSUE THREAD

**Issue by CyrosX** [rockdaboot/wget2#241]
Hello there! 
As the title suggests - It could be very useful to have an option
to prevent the creation of empty directories. (ex. mirroring a downloads directory from web)
Is it possible to implement this? :)

**Comment by rockdaboot** [comment]
Empty directories should normally not be created. Can you give me your command line options and/or an example debug output (add -d/--debug). Or if not possible for some reasons, give a detailed description ?
