### ISSUE TITLE
Script for downloading all the requirements for wget2?

### ISSUE THREAD

**Issue by Nestak2** [rockdaboot/wget2#246]
In the readme all the required packages for wget2 are listed in paragraph **Build Requirements**. Is there some kind of a script that I can run in my conda environment that installs all the necessary packages? I don't want to go 1-by-1 through them and copy-paste them into my terminal. Else wget2 looks really great, thanks for making this available!

**Comment by rockdaboot** [comment]
I have experience with conda and thus no idea how to install packages with it (or in it !?). I could add a list of packages e.g. for Debian testing or unstable.

If you already made a list / script and want to share it, just upload it here and I'll add it to the `contrib/` directory. Or you create a PR. Whatever you like.

**Comment by rockdaboot** [comment]
On `https://gitlab.com/gnuwget/build-images/` you can Dockerfiles in the docker-* directories for different Linux distros. In each `Dockerfile` there are commands for the installation of dependencies.

You can follow these commands and execute them locally (e.g. if you are on Fedora, pick `docker-fedora/Dockerfile`). But I'd suggest - if possible and feasible - to build the docker image and build wget2 inside a container.
