### ISSUE TITLE
'make' results in errors about "reference to gcry"

### ISSUE THREAD

**Issue by Nestak2** [rockdaboot/wget2#247]
I am trying to install wget2. I think I installed all the prerequisite packages (I skipped the optional ones), but maybe I missed something. 

So, I executed "./bootstrap", "./configure" and then with "make" I get a few error messages connected to "gcry" and the execution fails:

```
"/usr/bin/ld: ./.libs/libwget_hashfile.a(libwget_hashfile_la-hashfile.o): in function `wget_hash_init':
/home/nestor/Downloads/wget2/libwget/hashfile.c:578: undefined reference to `gcry_md_open'
/usr/bin/ld: ./.libs/libwget_hashfile.a(libwget_hashfile_la-hashfile.o): in function `wget_hash':
/home/nestor/Downloads/wget2/libwget/hashfile.c:587: undefined reference to `gcry_md_write'
/usr/bin/ld: ./.libs/libwget_hashfile.a(libwget_hashfile_la-hashfile.o): in function `wget_hash_deinit':
/home/nestor/Downloads/wget2/libwget/hashfile.c:593: undefined reference to `gcry_md_ctl'
/usr/bin/ld: /home/nestor/Downloads/wget2/libwget/hashfile.c:594: undefined reference to `gcry_md_read'
/usr/bin/ld: /home/nestor/Downloads/wget2/libwget/hashfile.c:595: undefined reference to `gcry_md_get_algo_dlen'
/usr/bin/ld: /home/nestor/Downloads/wget2/libwget/hashfile.c:596: undefined reference to `gcry_md_close'
/usr/bin/ld: ./.libs/libwget_hashfile.a(libwget_hashfile_la-hashfile.o): in function `wget_hash_get_len':
/home/nestor/Downloads/wget2/libwget/hashfile.c:559: undefined reference to `gcry_md_get_algo_dlen'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2896: test_linking_hashfile] Error 1
make[2]: Leaving directory '/home/nestor/Downloads/wget2/libwget'
make[1]: *** [Makefile:1827: all-recursive] Error 1
make[1]: Leaving directory '/home/nestor/Downloads/wget2'
make: *** [Makefile:1735: all] Error 2"
```

Apparently, it is some part of gnu, and it looks like I have to change settings of gnu, or configure gnu or something like this, I don't really know. This question seems similar to mine: https://stackoverflow.com/questions/11993417/undefined-reference-to-gcry-check-version-whats-wrong.

I am linking below the full outputs to the "./bootstrap", "./configure" and "make" commands.
https://drive.google.com/file/d/1rhTodP9TkmFqdno1Z2bptIvNyKc8MiM7/view?usp=sharing
https://drive.google.com/file/d/1J7QQB2p_dfOvAHFij4qqcRYSsfv_Hmm8/view?usp=sharing
https://drive.google.com/file/d/1L2cM3V1HvBiWTv3L_iwhaP2m6xrWAWLB/view?usp=sharing

Can you help me sort this out, so I can install the script? Tnx

**Comment by rockdaboot** [comment]
The `./configure` output tell me you have pkg-config installed - that is good.
But believe you don't have the development packages installed (ending with *-dev or *-devel). E.g. for GnuTLS, install `libgnutls28-dev` on Debian. Other distros have slightly different names, like -devel on Fedora.

If you have the development files of GnuTLS or OpenSSL installed, then libgcrypt will be skipped completely as both TLS libraries offer the needed hash functions.

If that doesn't help you, please provide `config.log`. It contains all the details of your system and likely I can see what is going wrong.
