### ISSUE TITLE
I have a list of urls with in a file how to make wget2 download the files one by one? and a question on display output

### ISSUE THREAD

**Issue by mhussaincov93** [rockdaboot/wget2#249]
hi there,
I have many urls in a file, how do I make wget2 download the files one by one?
as in one starts then finishes, then another starts?
also is it possible to have the old wget display?
I am blind and use a screen reader which does not play very well with the display output.
the first wget output works well.
the only thing i get with wget2 output is downloading then the name of file and nuthing other than that.
Majid

**Comment by rockdaboot** [comment]
Downloading one by one can be done with the two options --num-threads=1 and --no-http2.
If you do that, you possibly can also use the good old wget :-)

To have the same or very similar progress bar as wget has, use --progress=bar.
If you want this option be on by default, put this option into ~/wget2rc as a single line.

I hope this helps :-)

**Comment by mhussaincov93** [comment]
hi,
unknowne option --num-threads.
it says.
Majid

**Comment by rockdaboot** [comment]
Oh sorry, --max-threads=1 is it.

**Comment by mhussaincov93** [comment]
hey,
yep that seems to have worked :)
my thanks for your support :)

**Comment by rockdaboot** [comment]
NP, good to hear :-)

**Comment by rockdaboot** [comment]
Just realized, when there is a wget2rc file, wget2 says `~/.wget2rc is deprecated. Please move it to ~/.config/wget/wget2rc` :-)

To get rid of this message, just do what it says.
