### ISSUE TITLE
Statically linked binaries ?

### ISSUE THREAD

**Issue by chromer030** [rockdaboot/wget2#254]
Please provide statically linked binaries for compiled packages for OSs like Windows, macOS and Linux.

**Comment by rockdaboot** [comment]
You find the Windows executable (wget2.exe) at https://github.com/rockdaboot/wget2/releases/tag/v2.1.0 including a GPG signature.

With docker, it is now easy to build Win32 executables, see [instructions](https://github.com/rockdaboot/wget2/tree/master#build-static-wget2exe-on-gnulinux-for-windows).
