### ISSUE TITLE
[Logic Question] Why does the parser function have an **argv argument?

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#26]
I was going through the parser functions and noticed that ALL of them have a `const char *char * argv` argument which is marked as UNUSED. If we're not using this argument in any parser yet, is there any reason to keep it around?

Just trying to understand why that argument exists and how we're supposed to use it.

**Comment by rockdaboot** [comment]
Good point :-) At some point I changed the way the parser functions work. I guess I had some usage in mind for argv, but we have 'opt' now.
I removed the obsolete argv now.
