### ISSUE TITLE
wget2 stuck

### ISSUE THREAD

**Issue by Irbis01** [rockdaboot/wget2#261]
i tried to download http://f4se.silverlock.org from terminal or python(os.system). My wget2 sometimes gets stuck to 5-10 minutes and does not write anything to the log. In the end it loaded succesfully. Sometimes this time can be 10-15 minutes
command:
wget2 --no-cookies --mirror -e robots=off --max-threads=10 -D f4se.silverlock.org -P /home/user/download/f4se http://f4se.silverlock.org/

Most often this site is downloaded in 2 minutes.
most likely there is a timeout wait, but it takes a very long time. Perhaps it should be shortened with --timeout or is it still related to some kind of error? The process just hangs and doesn't log anything.

**Comment by rootkea** [comment]
Which wget2 version?

Wget2 1.99.1 on Ubuntu successfully downloads without getting stuck.

```
HTTP response 200 OK [http://f4se.silverlock.org/archive/f4se_0_06_21.7z]
Downloaded: 86 files, 29.29M bytes, 1 redirects, 0 errors
```

Most probably, it was a server issue.

PS - BTW, this makes me think we should show time taken to complete the wget2 command with average download rate maybe. Something like "Downloaded: 86 files, 29.29M bytes, in m minutes, with average download speed: s Kbps,1 redirects, 0 errors"

**Comment by Irbis01** [comment]
```
command: 
wget2 --version

result:
GNU Wget2 1.99.1 - multithreaded metalink/file/website downloader
+digest +https +ssl/gnutls +ipv6 +iri +large-file +nls -ntlm -opie +psl +iconv +idn2 +zlib +lzma +brotlidec +bzip2 +http2 +gpgm
```

**Comment by Irbis01** [comment]
I compare the number of downloaded files with the already downloaded site and their number is the same, but wget2 does not complete its work

**Comment by Irbis01** [comment]
Thanks. I am running wget from subprocess.Popen Python. I will try to repeat the same event in the terminal with the -d parameter

**Comment by Irbis01** [comment]
I tried to catch the error several times, but it only succeeded 3 times out of 15:
1. from terminal
2. from python code with subprocess.Popen

sometimes site downloaded quickly: about 10-30 second. At some times (when the log files are made) it took about 1.5 minutes and I stopped the work
[f4se.log](https://github.com/rockdaboot/wg
[obse_2.log](https://github.com/rockdaboot/wget2/files/8552214/obse_2.log)
et2/files/8552211/f4se.log)
[obse.log](https://github.com/rockdaboot/wget2/files/8552213/obse.log)

**Comment by Irbis01** [comment]
[f4se.log](https://github.com/rockdaboot/wget2/files/8552277/f4se.log)
[obse.log](https://github.com/rockdaboot/wget2/files/8552279/obse.log)
[obse_2.log](https://github.com/rockdaboot/wget2/files/8552280/obse_2.log)

**Comment by Irbis01** [comment]
What about this info? i catch this stuck sometimes

**Comment by rootkea** [comment]
I'm on a metered connection. So every download for me takes while. ;)

Last time this command took 5+ minutes for me! Therefore, I can't faithfully reproduce this speed/stuck issue at my end. At least not at the moment. But maybe others can?

Just hang in there and maintainers will reply. :)

**Comment by rockdaboot** [comment]
Since `GNU Wget2 1.99.1` we fixed a bunch of bugs. With the latest version from git master this issue is not reproducible.
I hope we soon find some time to make a new release.

**Comment by Irbis01** [comment]
Thank! we will wait the release

**Comment by rockdaboot** [comment]
The new release v2.0.1 is out: https://gitlab.com/gnuwget/wget2/-/tags/v2.0.1

**Comment by alexeyrakov01** [comment]
Thanks! We will try
