### ISSUE TITLE
Broken server gzip workaround actually breaks downloads

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#27]
There's a broken server gzip workaround in `libwget/http.c` in `wget_http_parse_response_header()`. 

```
	// a workaround for broken server configurations
	// see http://mail-archives.apache.org/mod_mbox/httpd-dev/200207.mbox/<3D2D4E76.4010502@talex.com.pl>
	if (resp->content_encoding == wget_content_encoding_gzip &&
		!wget_strcasecmp_ascii(resp->content_type, "application/x-gzip"))
	{
		debug_printf("Broken server configuration gzip workaround triggered\n");
		resp->content_encoding =  wget_content_encoding_identity;
	}
```

However, it is entirely possible that a server may decide to serve an application/x-gzip content-type by first running it through gzip. I just ran across this issue on a live server. 

The request was:

> GET /repo/fonts/infinality-bundle-fonts.db HTTP/1.1
> Host: bohoomil.com
> Accept-Encoding: gzip, deflate, bzip2, xz, lzma
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> User-Agent: Wget/2.0.0
> Connection: keep-alive

And the response came back:

> HTTP/1.1 200 OK
> Date: Sat, 24 Oct 2015 06:23:23 GMT
> Server: Apache/2.2.27 (CentOS)
> Last-Modified: Sat, 03 Oct 2015 22:59:16 GMT
> ETag: "e048a-1f0b3-5213b3abff900"
> Accept-Ranges: bytes
> Vary: Accept-Encoding
> Content-Encoding: gzip
> Connection: close
> Transfer-Encoding: chunked
> Content-Type: application/x-gzip

Here, the server actually does require the client to use gzip on the downloaded file to get a file of Content-Type: application/x-gzip. 

So, I guess, we should remove the workaround. Better to file bug reports for bad servers than not serve a file correctly from one that runs according to the RFC.

**Comment by rockdaboot** [comment]
You asked for a fonts.db, and the Server served double gzipped data ? Sounds broken... I would like To have  a closer look when i am back home.

**Comment by darnir** [comment]
Yes. But it explicitly mentioned so in the Response. It may not be the best idea, but it's legal.

**Comment by rockdaboot** [comment]
Yep, you are right. We should prefer correctly behaving servers over broken ones.
I commented the code and documented it a bit - just in case we need it later enabled by an additional CLI/config option.
Good that you found such a server - maybe you should tell them that they are wasting CPU time :-)
