### ISSUE TITLE
optimize download 

### ISSUE THREAD

**Issue by bphd** [rockdaboot/wget2#272]
I'm sorry, I know I should read the manual and that's what I did for half the day. But it's just too big

I was on wget and heard that wget2 can help me. I have a bad connection, I need to "optimize" the download by maximizing the bandwidth used to download the file, to keep going through line cut and being able to continue from partially downloaded file

I know that wget2 have those kind of options, but I need the name of them

**Comment by rockdaboot** [comment]
For downloading single files, it doesn't matter much whether you use wget or wget2. Both use all the bandwidth is available (can by cut-down by e.g. the remote server as well).

If the downloads stops, you should be able to continue it by starting the same command plus the `-c` option. If the server allows it (=suports the Range: header), then the download should continue. If the server doesn't support the Range header, no client can do anything but restart the download from 0.
