### ISSUE TITLE
ftp uri not parsed

### ISSUE THREAD

**Issue by tathastu871** [rockdaboot/wget2#273]
wget2 --user=xxx --password=xxx -r ftp://191.198.10.1/Tmp 
Failed to parse URI 'ftp:/
but wget2 --user=xxx --password=xxx -r ftp://191.198.10.1/Tmp 
works

**Comment by gvanem** [comment]
> but wget2 --user=xxx --password=xxx -r ftp://191.198.10.1/Tmp works

You mean `wget --user=xxx --password=xxx -r ftp://191.198.10.1/Tmp` works.
Well, duh! Since wget2 does not support ftp, that's why.
