### ISSUE TITLE
Chinese file name is garbled

### ISSUE THREAD

**Issue by goujibing** [rockdaboot/wget2#274]
I hope it can be solved.

**Comment by rockdaboot** [comment]
Can't help without further information. Can you run your wget2 command line with `--debug` added and post the ouput here ?

**Comment by goujibing** [comment]
For example: http://www.kangbidz.com/search/0/有源晶振.aspx  The file name after downloading is: %e6%9c%89%e6%ba%90%e6%99%b6%e6%8c%af.aspx

**Comment by goujibing** [comment]
Wget Chinese garbled solution https://www.programmerall.com/article/362524605/#:~:text=When%20downloading%20web%20pages%20with%20wget%2C%20if%20the,file%20that%20encodes%20the%20URL%20string%20is%20url.c.

**Comment by goujibing** [comment]
PS D:\工作文件> wget2 --debug
22.205844.948 name=debug value=(null) invert=0
22.205844.951 name=debug value=(null) invert=0
22.205844.953 Local URI encoding = 'CP936'
22.205844.955 Input URI encoding = 'CP936'
22.205844.957 Fetched HSTS data from 'C:\Users\gouji\AppData\Local/wget/.wget-hsts'
22.205844.960 Fetched HPKP data from 'C:\Users\gouji\AppData\Local/wget/.wget-hpkp'
22.205844.963 Fetched OCSP hosts from 'C:\Users\gouji\AppData\Local/wget/.wget-ocsp_hosts'
22.205844.966 Fetched OCSP fingerprints from 'C:\Users\gouji\AppData\Local/wget/.wget-ocsp'
22.205844.969 set_exit_status(0)
22.205844.971 queue_size: qsize=0
Nothing to do - goodbye

**Comment by rockdaboot** [comment]
> For example: http://www.kangbidz.com/search/0/有源晶振.aspx The file name after downloading is: %e6%9c%89%e6%ba%90%e6%99%b6%e6%8c%af.aspx

Here on Linux it looks like
```
-rw-r--r--  1 tim tim   113387 25. Nov 16:29  有源晶振.aspx
```

Can you try `wget2 --restrict-file-names=unix http://www.kangbidz.com/search/0/有源晶振.aspx` ?

**Comment by goujibing** [comment]
![image](https://user-images.githubusercontent.com/99847907/204165967-731f780e-1acd-40ae-9b3d-58334cd96a83.png)
command:  wget2 --restrict-file-names=unix -r -p -np -k http://www.kangbidz.com/ -o log.txt

**Comment by goujibing** [comment]
This is a GBK coding problem.

**Comment by rockdaboot** [comment]
I have no idea what to do about it. Wget2 uses the 3rd party iconv library for transcoding.
So it looks like something is broken outside the scope of wget2.

**Comment by goujibing** [comment]
I hope the following can help you：

wget中文乱码解决方案


下载网页时，若文件名含有非ASCII字符或其他特殊字符，就会出现所谓的乱码。若想解决中文乱码的问题，可以修改wget的源代码。
对URL[字符串]进行编码的源代码文件是url.c。其中，url_file_name()的功能是根据URL判断应该以什么文件名保存文件。而该函数又调用了append_uri_pathel()，该函数调用了FILE_CHAR_TEST()宏，它用于判断URL中的字符是不是特殊字符（也就是需要进行URL编码的字符。当然，包括中文）。问题就出在这个宏身上了。为了不对中文转义，需要将中文字符当作普通字符对待。将如下所示的FILE_CHAR_TEST()宏：

#define FILE_CHAR_TEST(c, mask) \
    ((opt.restrict_files_nonascii && !c_isascii ((unsigned char)(c))) || \
    (filechr_table[(unsigned char)(c)] & (mask)))

修改為：
#define FILE_CHAR_TEST(c, mask) \
(((opt.restrict_files_nonascii && !c_isascii ((unsigned char)(c))) || \
(filechr_table[(unsigned char)(c)] & (mask))) \
&& !((c|0x0fffffff) == 0xffffffff)) /* 排除中文 */

**Comment by goujibing** [comment]
Has this problem been solved?

**Comment by goujibing** [comment]
Has this problem been solved?
