### ISSUE TITLE
Bug: 'filter-urls' not working

### ISSUE THREAD

**Issue by troy-daniel** [rockdaboot/wget2#281]
After seeking the code, I finally find that, the 'filter-urls' settings in 'options.c' at line '1601' is not correct, where `args` (the first digit) should be `-1`, while current being `0`.

**Comment by rockdaboot** [comment]
> After seeking the code, I finally find that, the 'filter-urls' settings in 'options.c' at line '1601' is not correct, where `args` (the first digit) should be `-1`, while current being `0`.

Good spot ! Indeed, this prevents `--filter-urls=on` for example.

Maybe most people are using `--filter-urls` to switch it on or `--no-filter-urls` to switch it off 🤷🏻 

Fixed.
