### ISSUE TITLE
Windows build failed

### ISSUE THREAD

**Issue by sphoto** [rockdaboot/wget2#288]
Since b47114851973f56f999b9b206c73b7cca78c4cdd build on Windows is broken, because you accidentally removed the declaration of `tmplen`.

`io.c: In function 'wget_update_file':
io.c:425:14: error: 'tmplen' undeclared (first use in this function); did you mean 'mblen'?`

**Comment by rockdaboot** [comment]
Thanks, should be fixed since yesterday. Can you try the latest master ?

**Comment by rockdaboot** [comment]
Ah sorry, I forgot to sync the mirrors (this repo is a mirror of https://gitlab.com/gnuwget/wget2). Synced now.
