### ISSUE TITLE
Bunch of 0 byte files in download folder

### ISSUE THREAD

**Issue by sphoto** [rockdaboot/wget2#289]
I have a bunch of 0 byte files in the download folder when using the latest version of wget2. The files will remain, even if the download is complete.

`.wget-hpkp_lck
.wget-hsts_lck
.wget-ocsp_hosts_lck
.wget-ocsp_lck`

I never had those files (in the download folder) with previous versions.

EDIT: I found the bug. In latest `io.c` you have to exchange the code in lines 426 with 428 and 428 with 426.

**Comment by rockdaboot** [comment]
Thanks, fixed and pushed.
