### ISSUE TITLE
download the main page from a large list of domains

### ISSUE THREAD

**Issue by Rapid0nion** [rockdaboot/wget2#291]
Hello, please tell me, please, what options should I use to download the main page from a large list of domains, like:

domain1
domain2
domain3
...
domain1000

So that they are in different folders with their names?

**Comment by rockdaboot** [comment]
If you have a `urls.txt` file with e.g. the following content:
```
www.google.de
www.amazon.de
www.apple.de
```

Just do what you ask for with `wget2 -x -i urls.txt`.
