### ISSUE TITLE
Enabling cookies in libwget causes Segmentation Fault

### ISSUE THREAD

**Issue by ukll** [rockdaboot/wget2#301]
I am trying to learn using libwget with a simple example. Setting WGET_COOKIES_ENABLED to 1 causes Segmentation Fault.

I asked a question in [Stackoverflow](https://stackoverflow.com/questions/77672157/enabling-cookies-in-libwget-causes-segmentation-fault). All the details are provided in that page.

I need your help. Thanks.

**Comment by rockdaboot** [comment]
You SO question has been answered (https://stackoverflow.com/a/77674258/1987247).

For readers who don't want to jump on SO:

I'd suggest to build and install libwget (and wget2) from tarball. Instructions can be found at [here](https://gitlab.com/gnuwget/wget2#downloading-and-building-from-tarball).

Or upgrade your system to Debian testing to stay with relatively modern software versions without the downside of running a "bleeding edge" system.

**Comment by rockdaboot** [comment]
Btw, if you are interested the cookie fields, let me know. Libwget currently keep the `wget_cookie` type opaque, so you don't have direct access to the fields.
Also, there are no getters/setters for single fields, but I am open to add those if there is interest.

**Comment by rockdaboot** [comment]
To print out cookies you can currently do
```C
	for (int it = 0; it < wget_vector_size(resp->cookies); it++) {
		wget_cookie *cookie = wget_vector_get(resp->cookies, it);
		printf("got cookie %s\n", wget_cookie_to_setcookie(cookie));
	}
```
