### ISSUE TITLE
WolfSSL enhancement

### ISSUE THREAD

**Issue by sphoto** [rockdaboot/wget2#302]
Since wolfSSL 5.5.2 (Oct 2022) they added support for system CAs store, please see:
https://www.wolfssl.com/support-for-system-certificate-store-2/

This is a very helpful feature especially for Windows users since they usually don't have `config.ca_directory` or `config.ca_file` defined.

**Comment by rockdaboot** [comment]
Thanks for the heads up.
Just added with commit fb69b5d2809063e5c0141dc0f5062e82c787d001
