### ISSUE TITLE
Unexpected body length 221943546

### ISSUE THREAD

**Issue by wbtcpip2** [rockdaboot/wget2#303]
I have this problem:

[0] Downloading 'http://www.isgoodforyou.net/download/tv_program/IGFY.mp4' ...
Saving 'D:\GB32\Download\IGFY.mp4'
Just got 221943546 of 2260468422 bytes (http://www.isgoodforyou.net/download/tv_program/IGFY.mp4)
HTTP response 200 OK [http://www.isgoodforyou.net/download/tv_program/IGFY.mp4]
Unexpected body length 221943546.

is there any setting to try that will alow me to download that file?

**Comment by rockdaboot** [comment]
Did you try with
```
--ignore-length       Ignore content-length header field
```
?

**Comment by rockdaboot** [comment]
Btw, I just downloaded the file and it has 2260468422 bytes, as the content-length header states.

So likely the server closed the connection prematurely when you tried it.
