### ISSUE TITLE
Receivie HTTP 404 when using --accept flag

### ISSUE THREAD

**Issue by snpefk** [rockdaboot/wget2#305]
Hi! Thanks for your tool!

I tried to mirror a Maven repository without the actual artifacts, only html files. When I try to use the `--accept` flag to filter out all files except for `html`, I receive an HTTP 404 error while attempting to download. Here is how I do that: 

```shell
$ MAVEN_INDEX_TREE_DIR=$(mktemp --directory)
$ wget2 --recursive \
      --accept=html \
      --no-clobber \
      --html-extension \
      --no-parent \
      -o wget2-accept.log \
      --directory-prefix="$MAVEN_INDEX_TREE_DIR" \
      $maven_repository_url
```

And here is the log:

```shell
[1] Downloading '<maven repo url>/robots.txt' ...
HTTP ERROR response 404 [<maven repo url>/robots.txt]
[1] Checking '<maven repo url>' ...
HTTP ERROR response 404 [<maven repo url>]
```

The same set of arguments works with `wget`, and when I switch from `--accept` to `--reject` flags, everything works fine.

**Comment by rockdaboot** [comment]
Thanks for the report :)

Can you add the wget2 version and the system you are running on?

I tried the command line on some news site, but could not reproduce.
I'd like to try the `$maven_repository_url`, but understand that you don't want to post it here in public. Do you mind to send it to me directly via email? (find it in the git commits)

**Comment by snpefk** [comment]
Well, I tried to reproduce bug with Maven Central repository with 

```shell
$ MAVEN_INDEX_TREE_DIR=$(mktemp --directory)
$ USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0"
$ wget2 --user-agent "$USER_AGENT" \
      --accept=html,htm \
      --recursive \
      -e --robots=off \
      --no-clobber \
      --html-extension \
      --no-parent \
      --directory-prefix="$MAVEN_INDEX_TREE_DIR" \
      --verbose \
      https://repo.maven.apache.org/maven2/com/
```

and both version of wget are working with Maven Central, but refuse to work with our internal repository. So now I'm even more confused. I tried to debug request even more with `-d` flag, but any advice how to debug `wget2` is appreciated.

**Comment by snpefk** [comment]
I found out that `HEAD` requests are prohibited on our server, and I suppose this is why `wget2` isn't working. Here is the log from calling `wget2`:

```
[0] Checking '<maven-repository-url>' ...
19.152147.641 queue_size: qsize=1
19.152147.642 cookie_create_request_header for host=<maven-repository-url>
19.152147.642 HTTP2 stream id 3
19.152147.642 [0] action=1 pending=1 host=0x600000f843c0
19.152147.642 [0] action=2 pending=1 host=0x600000f843c0
19.152147.642   ##  pending_requests = 1
19.152147.642 [FRAME 3] > HEADERS
19.152147.642 [FRAME 3] > :method: HEAD
19.152147.642 [FRAME 3] > :path: <maven-repository-url-path>
19.152147.642 [FRAME 3] > :scheme: https
19.152147.642 [FRAME 3] > :authority: <maven-repository-url-host>
19.152147.642 [FRAME 3] > accept-encoding: gzip, deflate, bzip2, xz, lzma, br, zstd, lzip
19.152147.642 [FRAME 3] > accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
19.152147.642 [FRAME 3] > user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
19.152147.697 :status: 404
```
It seems that `wget` does not send `HEAD` requests and simply downloads pages with `GET`."

**Comment by snpefk** [comment]
Maybe is there a flag to disable `HEAD` requests checking?

**Comment by rockdaboot** [comment]
> Maybe is there a flag to disable `HEAD` requests checking?

Sorry for the late reply. There is no flag to switch off this behavior.

The two reasons for this are:
- I wasn't aware that servers don't support HEAD requests, at least it was never a "real world" problem so far.
- Just using a GET request would download every file, no matter how long it is. That is super wasteful if you just want to know the file type. Most of the files would be removed after downloading. This is not what you want (except as a work-around for bad server behavior).

I hesitate to add a CLI flag to enable this kind of weirdness just to address that internal server issue.

**Comment by snpefk** [comment]
> Sorry for the late reply. There is no flag to disable this behavior.

It's an **open-source software**, so there's no pressure to reply to online strangers. :)

> I wasn't aware that servers don't support HEAD requests; it has never been a "real world" problem so far.
> I hesitate to add a CLI flag to enable this kind of workaround just to address that internal server issue.

Well, I work at a very real company; it's not a poorly configured server from my hobby project. I asked our admins to add support for `HEAD` requests (but I lost the ticket). However, my main point in suggesting some flag or feature to acknowledge this behavior is to ensure backward compatibility, since the original `wget` handles this setup just fine. `wget2` is an amazing tool, and I hope I can use it alone without needing to occasionally fallback to its predecessor.

But decision is yours :)
