### ISSUE TITLE
Progress bar not easy to show current filename when downloaded files size > 1.

### ISSUE THREAD

**Issue by Ox0400** [rockdaboot/wget2#307]
Progress bar not easy to show current filename when downloaded files size > 1.

```
en_170.jsonl.zst      71% [===========================================>                                    ]   10.20G    8.75MB/s
2 files               52% [===============================================>                                  ]   18.47G   14.45MB/s

```

**Comment by Ox0400** [comment]
```
# libwget/bar.c
	if (slotp->numfiles == 1) {
		slotp->filename = wget_strdup(filename);
		slotp->file_size = 0;
		slotp->bytes_downloaded = 0;
	} else {
		slotp->filename = wget_aprintf("%d files", slotp->numfiles);
	}

```

**Comment by rockdaboot** [comment]
The bar for downloading two files should look like
```
Contents-amd64.gz.1  100% [=============================================================================>]   44.72M   27.17MB/s
Contents-amd64.gz    100% [=============================================================================>]   47.88M   29.67MB/s
                          [Files: 2  Bytes: 92.61M [53.28MB/s] Redirects: 0  Todo: 0  Errors: 0          ]
```
What environment (OS, shell, locale) are you running on? Which version of wget2 are you using?

**Comment by Ox0400** [comment]
> The bar for downloading two files should look like
> 
> ```
> Contents-amd64.gz.1  100% [=============================================================================>]   44.72M   27.17MB/s
> Contents-amd64.gz    100% [=============================================================================>]   47.88M   29.67MB/s
>                           [Files: 2  Bytes: 92.61M [53.28MB/s] Redirects: 0  Todo: 0  Errors: 0          ]
> ```
> 
> What environment (OS, shell, locale) are you running on? Which version of wget2 are you using?

Hi @rockdaboot, thanks for your reply, you can add `--max-threads 1` to get the same message(`2 files`).

System: `centos rhel fedora(amazon linux 2)`
```
#  wget2-2.1.0  wget2-latest.tar.gz
wget2 -V
GNU Wget2 2.1.0 - multithreaded metalink/file/website downloader
```

**Comment by rockdaboot** [comment]
> you can add --max-threads 1 to get the same message(2 files)

:+1: The makes it reproducible for me. I'll have a look at it in the next days.

**Comment by rockdaboot** [comment]
Fixed by https://gitlab.com/gnuwget/wget2/-/merge_requests/546 (still needs to be merged).
