### ISSUE TITLE
Exit status is 0 even when there is an error

### ISSUE THREAD

**Issue by mruprich** [rockdaboot/wget2#309]
I ran into this when trying a bit more complicated use case with https but than I noticed that even a simple download ends up with a zero exit status even when there is an error. I tried that on a non-existing website like this:
```
 # wget2 --tries=3 http://non-existing-web-for-wget.com

Failed to resolve 'non-existing-web-for-wget.com' (Name or service not known)
Failed to resolve 'non-existing-web-for-wget.com' (Name or service not known)
Failed to resolve 'non-existing-web-for-wget.com' (Name or service not known)

                          [Files: 0  Bytes: 0  [0 B/s] Redirects: 0  Todo: 0  Errors: 0         ]
# echo $?
0
```

This was quite similar for a use case with the server certificates (if needed I can try to create a reproducer here). In short, I used the --no-check-certificate option but the server was set up so that without ssl it would not allow a connection. wget then ended with these messages instead:
```
WARNING: The certificate is NOT trusted. The certificate issuer is unknown.
Failed to read 102400 bytes (hostname='xxxxxxx', ip=XX.XX.XX.XX, errno=11)
...
WARNING: The certificate is NOT trusted. The certificate issuer is unknown.
Failed to read 102400 bytes (hostname='xxxxxxx', ip=XX.XX.XX.XX, errno=11)
...
WARNING: The certificate is NOT trusted. The certificate issuer is unknown.
Failed to read 102400 bytes (hostname='xxxxxxx', ip=XX.XX.XX.XX, errno=11)
```

But even this scenario ended with an exit_status 0. Old wget would mark both of these as a network failure and return 4. Not saying wget2 should do the same, just trying to figure out whether this is a bug or not.

Thanks and regards,
Michal Ruprich

**Comment by rockdaboot** [comment]
Thanks for reporting. I'd consider this a bug.

**Comment by rockdaboot** [comment]
This has been fixed by https://gitlab.com/gnuwget/wget2/-/merge_requests/545
