### ISSUE TITLE
bug(windows): stdin/stdout modes of the calling process is not restored after wget2 exits

### ISSUE THREAD

**Issue by insomnimus** [rockdaboot/wget2#311]
On Windows, wget2 currently sets the console modes via `SetupConsoleHandle` in libwget (`console.c`) so that stdin gets `ENABLE_VIRTUAL_TERMINAL_INPUT`, and stdout `ENABLE_VIRTUAL_TERMINAL_PROCESSING`.

This seems to cause problems after wget2 exits (noticeably with input) on the default terminal conhost.exe, as well as the new Windows Terminal and likely others:
- Pressing `ctrl+enter`, instead of doing whatever action it should, inputs the character `j` into the terminal
- Pressing `ctrl+backspace`, instead of deleting to the left of the word, deletes a single character
- Pressing `ctrl+f` inputs the character `F`
- Customly assigned keybinds such as `ctrl+1` do nothing, including their action

These are just a couple - the problem isn't specific to any of these key combinations.

The solution I've figured out to this problem is restoring the initial console mode as obtained with `GetConsoleMode` before the program exits.
I've tested that restoring the initial modes before exit indeed solves the problem.

Since the console mode's set in libwget, ideally it should also be restored by libwget (maybe something to be called by the library user before exit).

**Comment by rockdaboot** [comment]
Fixed in master
