### ISSUE TITLE
Regression: console modes not being restored on windows

### ISSUE THREAD

**Issue by insomnimus** [rockdaboot/wget2#318]
- The main issue is #311; I couldn't reopen that issue for some reason.

Although this was fixed in 2b6bd2e1903c66d765ecb95a7e274f566d1acc51, it  was later broken again in 81cf05e1da1344fac0525569fdc87f4b4bfe005b.

I'll investigate what went wrong in that commit when I get a chance.

**Comment by insomnimus** [comment]
Yeah, it looks like something was lost / done differently. I'll take a look within a few days.

**Comment by sphoto** [comment]
The initital console modes were stored too late (src/wget.c), because `SetupConsoleHandle` (libwget/console.c) was called before. It should work if you move these lines
```
#ifdef _WIN32
    if (initial_stdin_mode == 0) GetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), &initial_stdin_mode);
    if (initial_stdout_mode == 0) GetConsoleMode(GetStdHandle(STD_OUTPUT_HANDLE), &initial_stdout_mode);
#endif
```
in front of `wget_global_init(0);`

**Comment by rockdaboot** [comment]
Thanks @sphoto, @insomnimus
Moved code further up, change has been pushed to the `master` branch.

Feel free to re-open if there still is an issue.
