### ISSUE TITLE
How to see server headers?

### ISSUE THREAD

**Issue by sHAsHiLx** [rockdaboot/wget2#319]
Tried to pass argument **--server-response** to see it and received following

![изображение](https://github.com/rockdaboot/wget2/assets/20460472/36027bf9-05a7-4f7f-a491-c05980b8dada)

In wget 1.x headers showed as requested

![изображение](https://github.com/rockdaboot/wget2/assets/20460472/441c50c8-b72f-4a0b-8698-0ec915f17321)

**Comment by rockdaboot** [comment]
Thanks for the report, this needs to be fixed.

As a work-around, add `--progress=none`.

**Comment by rockdaboot** [comment]
> Thanks for the report, this needs to be fixed.

Fixed in master.
