### ISSUE TITLE
Unknown option 'exclude-directories'

### ISSUE THREAD

**Issue by Zyles** [rockdaboot/wget2#320]
`$ wget2 --recursive --level 100 --no-hsts --adjust-extension --span-hosts --content-disposition --trust-server-names --cut-file-get-vars --exclude-directories=/wp-content --domains sub.domain.com --no-parent sub.domain.com`

Error:

Unknown option 'exclude-directories'

Wget version:
```
$ wget2 --version
GNU Wget2 1.99.1 - multithreaded metalink/file/website downloader

+digest +https +ssl/gnutls +ipv6 +iri +large-file +nls -ntlm -opie +psl +iconv +idn2 +zlib +lzma +brotlidec +bzip2 +http2 +gpgme
```

Please advice.

**Comment by rockdaboot** [comment]
Please update to a newer version. 1.99.1 is totally outdated.

**Comment by Zyles** [comment]
This is on latest Ubuntu.

Can the packages be updated?

Building from source is a real pain.

**Comment by rockdaboot** [comment]
> This is on latest Ubuntu.

Latest Ubuntu (24.04LTS) has Wget2 v2.1.0.
See also https://packages.ubuntu.com/search?keywords=wget2
