### ISSUE TITLE
Handling HTTP/1.0 Responses in an HTTP/1.1 Proxy

### ISSUE THREAD

**Issue by SUnRedKing** [rockdaboot/wget2#323]
Hello,

I'm currently working with an HTTP proxy where the response is hardcoded to HTTP/1.1 200. However, there are cases where the response could be HTTP/1.0 200. How should I handle this situation?

I noticed that in wget1, it parses the response status to obtain the status code.

Could you provide some guidance or best practices for handling this scenario?

Thank you.

**Comment by rockdaboot** [comment]
This has been fixed in `master`, see https://gitlab.com/gnuwget/wget2/-/issues/666
