### ISSUE TITLE
Error due to brotli:

### ISSUE THREAD

**Issue by rzhy1** [rockdaboot/wget2#326]
Error due to brotli:
Why does version wget2-2.1.0 fail whenever brotli is used when compiling to an exe file, and in the wget2/contrib/Dockerfile.win32.static file, regarding brotli, -DCMAKE_INSTALL_PREFIX=/home/tim/src/ wget2/x86_64-w64-mingw32, is it because it's incompatible, so you changed the path specifically? Any solution for that?

**Comment by rockdaboot** [comment]
Reproducible, even when replacing `-DCMAKE_INSTALL_PREFIX=/home/tim/src/ wget2/x86_64-w64-mingw32` with `-DCMAKE_INSTALL_PREFIX=$INSTALLDIR`.

The brotli installation looks good:
```
[100%] Built target brotli
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/x86_64-w64-mingw32/bin/brotli
-- Installing: /usr/local/x86_64-w64-mingw32/lib/libbrotlienc.a
-- Installing: /usr/local/x86_64-w64-mingw32/lib/libbrotlidec.a
-- Installing: /usr/local/x86_64-w64-mingw32/lib/libbrotlicommon.a
-- Installing: /usr/local/x86_64-w64-mingw32/include/brotli
-- Installing: /usr/local/x86_64-w64-mingw32/include/brotli/decode.h
-- Installing: /usr/local/x86_64-w64-mingw32/include/brotli/shared_dictionary.h
-- Installing: /usr/local/x86_64-w64-mingw32/include/brotli/port.h
-- Installing: /usr/local/x86_64-w64-mingw32/include/brotli/encode.h
-- Installing: /usr/local/x86_64-w64-mingw32/include/brotli/types.h
-- Installing: /usr/local/x86_64-w64-mingw32/lib/pkgconfig/libbrotlicommon.pc
-- Installing: /usr/local/x86_64-w64-mingw32/lib/pkgconfig/libbrotlidec.pc
-- Installing: /usr/local/x86_64-w64-mingw32/lib/pkgconfig/libbrotlienc.pc
-- Installing: /usr/local/x86_64-w64-mingw32/share/man/man1/brotli.1
-- Installing: /usr/local/x86_64-w64-mingw32/share/man/man3/constants.h.3
-- Installing: /usr/local/x86_64-w64-mingw32/share/man/man3/decode.h.3
-- Installing: /usr/local/x86_64-w64-mingw32/share/man/man3/encode.h.3
-- Installing: /usr/local/x86_64-w64-mingw32/share/man/man3/types.h.3
```

But then, it looks like some functions are missing.
```
/usr/bin/x86_64-w64-mingw32-ld: ../libwget/.libs/libwget.a(libwget_la-decompressor.o):decompressor.c:(.text+0xa9): undefined reference to `BrotliDecoderDecompressStream'
/usr/bin/x86_64-w64-mingw32-ld: ../libwget/.libs/libwget.a(libwget_la-decompressor.o):decompressor.c:(.text+0x122): undefined reference to `BrotliDecoderGetErrorCode'
/usr/bin/x86_64-w64-mingw32-ld: ../libwget/.libs/libwget.a(libwget_la-decompressor.o):decompressor.c:(.text+0x129): undefined reference to `BrotliDecoderErrorString'

... and so on ...
```

Need to look into it.

**Comment by rzhy1** [comment]
when replacing with .-DCMAKE_INSTALL_PREFIX=/home/tim/src/ wget2/x86_64-w64-mingw32-DCMAKE_INSTALL_PREFIX=$INSTALLDIR
The brotli installation looks good,But compiling gnutls also gives errors。

**Comment by rockdaboot** [comment]
Yeah, maybe something with the brotli build changed. Maybe check out a specific version after git clone. I try if time allows

**Comment by rockdaboot** [comment]
Maybe brotli doesn't support Winodws cross-build with MinGW. I fail to find any documentation - even an internet search stays pretty silent.
As you say, the installation looks good, but I assume the `.a` files are in a wrong format.

I am not an expert on building brotli nor on cross-building. The only thing I can do is removing brotli from the Dockerfile 🤷🏻
