### ISSUE TITLE
File downloaded as an html page instead of a .txt file

### ISSUE THREAD

**Issue by mruprich** [rockdaboot/wget2#337]
Running wget2 on a .txt file on dropbox does not download the actual file but rather an html page:
```
# wget2 -qO - 'https://www.dropbox.com/scl/fi/uryzfd2i7rgwr5my5lqod/hello.txt?rlkey=guhp9wxm1x8caqtd7a9qbo62d&st=11px7sc4&dl=0'
<!DOCTYPE html>
<html class="maestro global-header" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head><meta charset="utf-8" />
...
...
</script><script nonce="xaep3Xr5nsBfG9w05&#43;ikUJpGT24=" async src="/page_success/end?edison_page_name=scl_oboe_file&amp;path=%2Fscl%2Ffi%2Furyzfd2i7rgwr5my5lqod%2Fhello.txt&amp;request_id=97c8a4d93f7348279ce1ce123e1f43d2&amp;time=1724052721" crossorigin="anonymous"></script>
</body></html><!--status=200-->
```
With wget1 the actual file and its contents are printed:
```
# wget -qO - 'https://www.dropbox.com/scl/fi/uryzfd2i7rgwr5my5lqod/hello.txt?rlkey=guhp9wxm1x8caqtd7a9qbo62d&st=11px7sc4&dl=0'
Hello world.
# 
```
I tried --spider with the old wget (the new one does not have this info in the output) and it says that the file is considered [application/json]. But wget1 could download it fine.

Regards,
Michal Ruprich

**Comment by rockdaboot** [comment]
The request headers send by wget1 and wget2 are slightly different. Some servers inspect the headers and provide content based on what they think is best for the request.

In many cases servers look at the User-Agent header, but it can also be the Accept-Encoding header that results in different server behavior. I can't reproduce with the URLs from your description, the response is always empty for me.

**Comment by rockdaboot** [comment]
You can see with `--debug` what the difference is. E.g. wget2 may use http2, so a first try could be with `--no-http2` to use the same protocol as wget1 does.

**Comment by rockdaboot** [comment]
@mruprich Please feel free to reopen when you have more information or a reproducer that works for anybody but you.

**Comment by mruprich** [comment]
@rockdaboot Sorry, forgot about this one. Not sure how to reopen though, I do not see any option like that.

The dropbox file is generally available for anyone so you can actually test yourself (I think that is what you meant by a reproducer that works for anybody but me). --no-http2 has the same result as the original command. Any other trick I could try?

Regards,
Michal

**Comment by mruprich** [comment]
Just one more note, I tried to temper a bit with the header by using --header-line to make it a bit more like wget1 header and it still does not get the file (both --no-http2 and with default http2). I noticed that with wget1 the response is 302 at first and then it gets redirected to a different location and the second response receives Content-type: text/plain. wget2 get 200 right away and downloads the webpage with Content-type: text/html..

**Comment by mruprich** [comment]
So it was as you suggested caused by the user-agent. I was focusing on the part where for wget1 and for curl, dropbox would return 302 Found first and a location header and then it would get the second header with 200 OK and download the file. Using wget2 with either --user-agent="Wget/1.21.4" or --header='user-agent: Wget/1.21.4' actually got dropbox to return 302 and then 200.

After at least getting wget2 to get to this point, something weird happens. wget2 actually shows the download progress but always stops at 50% and stops, no file is actually downloaded...

**Comment by rockdaboot** [comment]
Sniffing for the user agent on the server is a very old topic that pops up again and again (see https://en.wikipedia.org/wiki/Browser_wars). But too many people simply don't learn from history.

Given that nobody in larger companies cares at all (maybe too busy implementing more shitty stuff), I think about using the executable name as first part of the user agent string.
It would help the Fedora user at least and would be backwards compatible.

@mruprich Can you test with `--header='user-agent: Wget/2.1.0', please?

**Comment by mruprich** [comment]
Thanks for the response, I honestly had no idea that this is how the user-agent is being used. I tried as you suggested and seems like a correct response is returned by the server, a couple of lines from the --debug output below:
`16.192911.121 HTTP2 stream id 1
16.192911.121 [0] action=1 pending=1 host=0x55f2ef735990
16.192911.121 [0] action=2 pending=1 host=0x55f2ef735990
16.192911.121   ##  pending_requests = 1
16.192911.121 [FRAME 0] > SETTINGS
16.192911.121 [FRAME 0] > WINDOW_UPDATE
16.192911.121 [FRAME 1] > HEADERS
16.192911.121 [FRAME 1] > :method: GET
16.192911.121 [FRAME 1] > :path: /scl/fi/uryzfd2i7rgwr5my5lqod/hello.txt?rlkey=guhp9wxm1x8caqtd7a9qbo62d&st=11px7sc4&dl=0
16.192911.121 [FRAME 1] > :scheme: https
16.192911.121 [FRAME 1] > :authority: www.dropbox.com
16.192911.121 [FRAME 1] > accept-encoding: gzip, deflate, br, zstd
16.192911.121 [FRAME 1] > accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
16.192911.121 [FRAME 1] > user-agent: Wget/2.1.0
16.192911.152 [FRAME 0] < SETTINGS
16.192911.152 [FRAME 0] < WINDOW_UPDATE
16.192911.152 [FRAME 0] > SETTINGS
16.192911.152 [FRAME 0] < SETTINGS
16.192911.672 :status: 302
16.192911.672 content-security-policy: frame-src https://* ....
...
16.192911.825 HTTP2 stream id 1
16.192911.825 [0] action=1 pending=1 host=0x7f67a8ddfbb0
16.192911.825 [0] action=2 pending=1 host=0x7f67a8ddfbb0
16.192911.825   ##  pending_requests = 1
16.192911.825 [FRAME 0] > SETTINGS
16.192911.825 [FRAME 0] > WINDOW_UPDATE
16.192911.825 [FRAME 1] > HEADERS
16.192911.825 [FRAME 1] > :method: GET
16.192911.825 [FRAME 1] > :path: /cd/0/inline/CejwdRCSL5k3_qL8_ltcs-AEclEhDOoO23Xz83oqLDF9XKWdTLIDP_HWpTFsOubictXxIQygszJ_ztGMk_fhQPqWsxe4SI3I-oZal3kk7HFOQnLHVWaNHIaUhZ_oZp_NvpM/file
16.192911.825 [FRAME 1] > :scheme: https
16.192911.825 [FRAME 1] > :authority: ucd4905a11e1a26282ae80a27e81.dl.dropboxusercontent.com
16.192911.825 [FRAME 1] > accept-encoding: gzip, deflate, br, zstd
16.192911.825 [FRAME 1] > accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
16.192911.825 [FRAME 1] > user-agent: Wget/2.1.0
16.192911.856 [FRAME 0] < SETTINGS
16.192911.856 [FRAME 0] < SETTINGS
16.192911.856 [FRAME 0] < WINDOW_UPDATE
16.192911.856 [FRAME 0] > SETTINGS
16.192912.128 :status: 200
16.192912.128 content-type: text/plain; charset=utf-8
16.192912.128 accept-ranges: bytes
16.192912.128 cache-control: max-age=60
16.192912.128 content-disposition: inline; filename="hello.txt"; filename*=UTF-8''hello.txt
16.192912.128 content-security-policy: report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-usercontent ; sandbox allow-forms allow-scripts allow-top-navigation allow-popups
16.192912.128 content-security-policy: form-action 'none' ; report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-noscript ; script-src 'none'
16.192912.128 etag: 1717943228061276d
16.192912.128 pragma: public
16.192912.128 referrer-policy: no-referrer
16.192912.128 [FRAME 1] > RST_STREAM
16.192912.128 closing stream 1
16.192912.128   ##  response status 200
16.192912.128 keep_alive=1
16.192912.128 _host_remove_job: 0x7f67a8de0810
16.192912.128 host_remove_job: qsize=0 host->qsize=0
16.192912.128 [0] action=1 pending=0 host=0x7f67a8ddfbb0
16.192912.128 closing connection
16.192912.128 [0] action=1 pending=0 host=0x0
16.192912.129 main: wake up
16.192912.129 main: done
16.192912.130 Successfully updated '/home/mruprich/.local/share/wget/.wget-hsts'.
16.192912.130 Saved 5 HSTS entries into '/home/mruprich/.local/share/wget/.wget-hsts'
16.192912.130 blacklist https://www.dropbox.com/scl/fi/uryzfd2i7rgwr5my5lqod/hello.txt?rlkey=guhp9wxm1x8caqtd7a9qbo62d&st=11px7sc4&dl=0
16.192912.130 blacklist https://ucd4905a11e1a26282ae80a27e81.dl.dropboxusercontent.com/cd/0/inline/CejwdRCSL5k3_qL8_ltcs-AEclEhDOoO23Xz83oqLDF9XKWdTLIDP_HWpTFsOubictXxIQygszJ_ztGMk_fhQPqWsxe4SI3I-oZal3kk7HFOQnLHVWaNHIaUhZ_oZp_NvpM/file#`

Now the weird part is that the file is actually neither downloaded nor printed out. I don't see any error but at the same time, seems like nothing happens..

**Comment by mruprich** [comment]
Testing one more time without the -q0, the actual download shows just 50% as I described above:
```
16.193243.428 HTTP2 stream id 1
16.193243.428 [0] action=1 pending=1 host=0x7fbae40d6dd0
16.193243.428 [0] action=2 pending=1 host=0x7fbae40d6dd0
16.193243.428   ##  pending_requests = 1
16.193243.428 [FRAME 0] > SETTINGS
16.193243.428 [FRAME 0] > WINDOW_UPDATE
16.193243.428 [FRAME 1] > HEADERS
16.193243.428 [FRAME 1] > :method: GET
16.193243.428 [FRAME 1] > :path: /cd/0/inline/CehImF580yiKKtRWX1VjTEDC27CRdaIebgsWRhfmJGZhVt0u3o9DNkmNBjn34SDApf37K7U6YXQpzl00C6aYutQtkvTHyhJQP1T6Q7AxJ-xn82OucPXfBCdWH0nAmrm2S8M/file
16.193243.428 [FRAME 1] > :scheme: https
16.193243.428 [FRAME 1] > :authority: uc11c229874fd356386f5fc369db.dl.dropboxusercontent.com
16.193243.428 [FRAME 1] > accept-encoding: gzip, deflate, br, zstd
16.193243.428 [FRAME 1] > accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
16.193243.428 [FRAME 1] > user-agent: Wget/2.1.0
16.193243.461 [FRAME 0] < SETTINGS
16.193243.461 [FRAME 0] < SETTINGS
16.193243.461 [FRAME 0] < WINDOW_UPDATE
16.193243.461 [FRAME 0] > SETTINGS
16.193243.892 :status: 200
16.193243.892 content-type: text/plain; charset=utf-8
16.193243.892 accept-ranges: bytes
16.193243.892 cache-control: max-age=60
16.193243.892 content-disposition: inline; filename="hello.txt"; filename*=UTF-8''hello.txt
16.193243.892 content-security-policy: report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-usercontent ; sandbox allow-forms allow-scripts allow-top-navigation allow-popups
16.193243.892 content-security-policy: form-action 'none' ; report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-noscript ; script-src 'none'
16.193243.892 etag: 1717943228061276d
16.193243.892 pragma: public
16.193243.892 referrer-policy: no-referrer
16.193243.892 [FRAME 1] > RST_STREAM
0 files               50% [=================================>                                   ]      17     --.-KB/s
16.193243.892   ##  response status 200
16.193243.892 keep_alive=1
16.193243.892 _host_remove_job: 0x7fbae4de1230
16.193243.892 host_remove_job: qsize=0 host->qsize=0
16.193243.892 [0] action=1 pending=0 host=0x7fbae40d6dd0
16.193243.892 closing connection
16.193243.892 [0] action=1 pending=0 host=0x0
16.193243.893 main: wake up
16.193243.893 main: done
16.193243.893 queue_size: [Files: 1  Bytes: 17  [6 B/s] Redirects: 1  Todo: 0  Errors: 0        ]
16.193243.894 Successfully updated '/home/mruprich/.local/share/wget/.wget-hsts'.
16.193243.894 Saved 5 HSTS entries into '/home/mruprich/.local/share/wget/.wget-hsts'
16.193243.894 blacklist https://www.dropbox.com/scl/fi/uryzfd2i7rgwr5my5lqod/hello.txt?rlkey=guhp9wxm1x8caqtd7a9qbo62d&st=11px7sc4&dl=0
16.193243.894 blacklist https://uc11c229874fd356386f5fc369db.dl.dropboxusercontent.com/cd/0/inline/CehImF580yiKKtRWX1VjTEDC27CRdaIebgsWRhfmJGZhVt0u3o9DNkmNBjn34SDApf37K7U6YXQpzl00C6aYutQtkvTHyhJQP1T6Q7AxJ-xn82OucPXfBCdWH0nAmrm2S8M/file#
```

**Comment by rockdaboot** [comment]
The server sends a header but immediately closes the HTTP/2 stream (`[FRAME 1] > RST_STREAM`).
The 50% progress bar looks like a race condition. We can ignore it for this GH issue.

Can you do the same with `--no-http2` added to the command line?

**Comment by rockdaboot** [comment]
Thanks.
It's '-O-', not just '-' ;)

**Comment by mruprich** [comment]
Aaah, right, so I tried with -O- and the output is the same as above - file is not printed :(

**Comment by mruprich** [comment]
```
wget2 --no-http2 --debug --header='user-agent: Wget/2.1.0' -O- 'https://raw.githubusercontent.com/rockdaboot/wget2/refs/heads/master/README.md'
```
This works just fine, I wonder what is special about the file from dropbox. It is saved as 'hello.txt?rlkey=guhp9wxm1x8caqtd7a9qbo62d&st=11px7sc4&dl=0' instead of just 'hello.txt', I wonder why. The above command works also simply as:
```
wget2 -O- 'https://raw.githubusercontent.com/rockdaboot/wget2/refs/heads/master/README.md'
```

**Comment by rockdaboot** [comment]
For some reason, the one-liner "Hello world." is overwritten by the progress bar. Ths works:
```
$ wget2 -q -O- --no-http2 --header='user-agent: Wget/2.1.0' 'https://www.dropbox.com/scl/fi/uryzfd2i7rgwr5my5lqod/hello.txt?rlkey=guhp9wxm1x8caqtd7a9qbo62d&st=11px7sc4&dl=0'
Hello world.

```
