### ISSUE TITLE
Add support for Basic Access credentials in URLs

### ISSUE THREAD

**Issue by markus456** [rockdaboot/wget2#338]
`wget` supports HTTP Basic Access authentication credentials in the URLs but `wget2` does not.

Here's an example URL that works elsewhere:
```
wget https://user:password@my-site.net/foo.tar.gz
```

A "workaround" to this is to pass the credentials with `--password` and `--user`:
```
wget --user=user --password=password https://my-site.net/foo.tar.gz
```
This isn't ideal as you have to be aware of the need for credentials and you can't simply process a URL even if the necessary credentials are included.

I tested both `curl` and Chrome and they seem to support this syntax for specifying credentials in the URL.

**Comment by rockdaboot** [comment]
From RFC 1738 (Uniform Resource Locators, 1994):
```
The use of URLs containing passwords that should be secret is clearly
   unwise.
```
 
The Update from 1998, https://www.ietf.org/rfc/rfc2396.html#section-3.2.2 makes it more clear:
```
Some URL schemes use the format "user:password" in the userinfo
   field. This practice is NOT RECOMMENDED, because the passing of
   authentication information in clear text (such as URI) has proven to
   be a security risk in almost every case where it has been used.
```

And I agree that no matter how cautious you are, using user:password as part of the userinfo in a URL may blow up any time. So while wget 1.x (and curl) has to support it for backwards compatibility, I hesitate to add support it with wget2.

Did you consider using `.netrc` as an alternative? It allows specifying user/password per domain/hostname or per IP without exposing the secrets via command line or URL (URLs often appear in logs). For interactive sessions, please also think of using `--ask-password` or `--use-askpass=command`.

**Comment by markus456** [comment]
Yeah, I have to agree after reading those that it's a smart policy to not implement this. The main use that I had for this was mostly for convenience: sometimes I need to download a file from a server inside a container or a VM and the fastest way was to copy-paste the link with embedded credentials into the container.

Perhaps it would be good to have a separate document that lists incompatibilities with `wget` that won't be fixed. This way it'd be easy to find out why some things don't work. Having recently upgraded to Fedora 40 where `wget` is `wget2`, there were a few things that surprised me.
