### ISSUE TITLE
Downloads do not complete - inconsistent 

### ISSUE THREAD

**Issue by danoli3** [rockdaboot/wget2#339]
For some bizarre reason some WGET2 downloads are not completing - randomly 

macOS, windows...

```
wget2 -N -nv --progress=bar --tries=20 --max-redirect=20 --retry-connrefused --timeout=1500 --waitretry=4 --compression=gzip --compression=br ${FINAL_EXTRA_ARGS} ${URLS_TO_DOWNLOAD}
```

Any ideas? It seems like when downloading multiple files after 1 or 2 finish and there is 3, the third gets disconnected and doesn't finish.

**Comment by rockdaboot** [comment]
Can you give me more details about the wget2 version you are using?
From what commit is it built?

I can't reproduce on Linux when building from latest master branch. Can you give the contents of your env variables or anything else that reproduces the issue?

**Comment by rockdaboot** [comment]
Is it possible that there is something wrong with your downloader script?
`$URLS` contains 4 urls, as in your comment above.
Then `downloader $URLS` sometimes fetches all 4 files:
```
$ downloader $URLS
 [openFrameworks downloader v4.3.1] ... 
  [downloader] enabled brotli/zlib losslesss compression response
  [downloader] check if local == remote: [https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_android_arm64.zip]
  [downloader] No download cache
  [downloader] Proceeding with download. 
  [downloader] check if local == remote: [https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_emscripten_memory64_pthreads.tar.bz2]
  [downloader] No download cache
  [downloader] Proceeding with download. 
  [downloader] check if local == remote: [https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_osx_3.tar.bz2]
  [downloader] No download cache
  [downloader] Proceeding with download. 
  [downloader] check if local == remote: [https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_vs_arm64ec_1.zip]
  [downloader] No download cache
  [downloader] Proceeding with download. 

  [downloader] [wget2] urls:[https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_android_arm64.zip https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_emscripten_memory64_pthreads.tar.bz2 https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_osx_3.tar.bz2 https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_vs_arm64ec_1.zip] args:[ --compression=gzip
```

But most of the time, it just tries to download a single file. (I removed all files before running the download):
```
$ downloader $URLS
 [openFrameworks downloader v4.3.1] ... 
  [downloader] enabled brotli/zlib losslesss compression response
  [downloader] check if local == remote: [https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_android_arm64.zip]
  [downloader] No download cache
  [downloader] Proceeding with download. 

  [downloader] [wget2] urls:[https://github.com/openframeworks/apothecary/releases/download/bleeding/openFrameworksLibs_bleeding_android_arm64.zip] args:[ --compression=gzip
```

**Comment by rockdaboot** [comment]
Sorry, just got aware that `downloader $URLS` changes the `$URLS` variable.

With the latest wget2, I can't reproduce the described error.
My assumption is that your installed version uses TCP FastOpen. Meanwhile, multiple issues have been reported that some middleboxes and/or firewalls don't handle TFO correctly (a shame, we have that technology since 2014).
Because of this, TFO is now disabled by default (commit 2b1f266ca639b7712a973c1512a2611d5fce7930). Please make sure you disable it explicitly with `--no-tcp-fastopen`. I am curious if that fixes your issue.

**Comment by danoli3** [comment]
```--no-tcp-fastopen```

does indeed fix it!!! tested windows only so far
