### ISSUE TITLE
Serious wget2 regression with HTTP 102

### ISSUE THREAD

**Issue by purpleidea** [rockdaboot/wget2#340]
No idea, but wget all of a sudden broke all my scripts. It just ends without downloading the file...

```
$ /usr/bin/wget -vvvv http://192.168.42.1:4280/fedora/releases/40/Everything/x86_64/os/images/pxeboot/vmlinuz 
0 files                0% [<=>                               ]       0          B/s
                          [Files: 0  Bytes: 0  [0 B/s] Redire]
$ echo $?
0
```

I've used wget for AGES, and it always just worked. Now I'm scratching my head... It's download from a custom golang http server. After lots of bisecting, I removed this line:

> w.WriteHeader(http.StatusProcessing) // http 102, RFC 2518, 10.1

And now things work normally again.

Curl works perfectly with either version of my code.

I guess this is a major bug and regression!

If you want to see how to reproduce this, just look here and run this to get an http server. Any non-cached wget will trigger it:

https://purpleidea.com/blog/2024/03/27/a-new-provisioning-tool/

```
 wget --version
GNU Wget2 2.1.0 - multithreaded metalink/file/website downloader

+digest +https +ssl/gnutls +ipv6 +iri +large-file +nls -ntlm -opie +psl -hsts
+iconv +idn2 +zlib -lzma +brotlidec +zstd -bzip2 -lzip +http2 +gpgme

Copyright (C) 2012-2015 Tim Ruehsen
Copyright (C) 2015-2021 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Please send bug reports and questions to <bug-wget@gnu.org>.

```

**Comment by rockdaboot** [comment]
Thanks for reporting.
1xx responses are rarely seen and it looks like nobody ever tested this scenario with wget2.
It needs a test and a fix of course.

**Comment by purpleidea** [comment]
>  It needs a test and a fix of course.
I'm sorry I don't have cycles to do that atm, but you are welcome to ping if you're having trouble making this repro.

I guess I win the bug finding contest \0/

**Comment by rockdaboot** [comment]
After reading a bit, it looks like 102 is not HTTP, but has been introduced as a WEBDAV extension (RFC 2518). Later, it has been removed with RFC 4918.

You should not use 102 status at all, no matter if/when future versions of wget2 support.

There is some valuable information in this SO thread: https://stackoverflow.com/questions/53238328/why-was-http-status-code-102-removed-from-http-1-1

**Comment by purpleidea** [comment]
Neat! It's still a regression versus wget1. Isn't it something we want to maintain? Most libraries still have this header... Can't imagine how many people use it.

If anything it's still a bug that this didn't exit non-zero.

**Comment by purpleidea** [comment]
Or just ignore the header and proceed normally...

**Comment by rockdaboot** [comment]
Yeah, we should ignore the 1xx responses.

**Comment by purpleidea** [comment]
So I don't think it has actually been "removed". Looks valid to me: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml whether wget does something intelligent with it or not is debatable, but at least atm this is a serious bug of how it's handling it which is barfing with a 0 exit code =D

**Comment by purpleidea** [comment]
Thanks for looking into this anyways. It's not urgent for me, I did a workaround, but hope the report was helpful for everyone else who might hit this. Cheers

**Comment by rockdaboot** [comment]
> So I don't think it has actually been "removed". Looks valid to me

Just to clarify: IANA has been advised to keep 102 in their list to make sure that 102 would never ever be re-used accidentally. Which makes sense if you think of the mess that could happen if two different definitions are used in the internet in parallel.

Anyway, it would be helpful if you could provide an endpoint/URL to test with. It looks like that our testing library, libmicrohttpd, doesn't support 1xx responses.

**Comment by rockdaboot** [comment]
There is a fix at https://gitlab.com/gnuwget/wget2/-/merge_requests/554/diffs if you want to test the changes.
I had to use `nc` for manual testing. As mentioned above, libmicrohttpd doesn't support 1xx responses, so we won't have automated tests for now.
