### ISSUE TITLE
Missing wget2 bash autocomplete file

### ISSUE THREAD

**Issue by FilipeBento** [rockdaboot/wget2#341]
I have just compiled and installed wget2 on Ubuntu WSL2. I am missing a wget2 auto-complete file, so I am unable to write 

`user@ubuntu$ wget2 --<TAB>` and check all the available flags. I know I can check the man page, but having an autocomplete file would be a great quality-of-life improvement. I don't have enough knowledge to build one.

My apologies if I missed something in the process.

(... and thank you for all your work!)

**Comment by rockdaboot** [comment]
Hm, it possibly doesn't make much sense for the old version. But let the packagers decide.
