### ISSUE TITLE
Error checking for SSL_read and SSL_write is off by one which can lead to an infinite loop

### ISSUE THREAD

**Issue by tobiasb-ms** [rockdaboot/wget2#342]
NOTE: I only encounter this when I see an odd networking issue on a VM that I'm still root causing. However, at first pass it does seem to be a bug in `wget2` that the networking issue is surfacing.

In `ssl_openssl.c`, in the function [ssl_transfer](https://github.com/rockdaboot/wget2/blob/ec27488feadd44b5e126592bc18ff2441f8cae5a/libwget/ssl_openssl.c#L1786), the check on the return value from `SSL_read` or `SSL_write` (depending on `want` parameter) [considers 0 a success](https://github.com/rockdaboot/wget2/blob/ec27488feadd44b5e126592bc18ff2441f8cae5a/libwget/ssl_openssl.c#L1819). The [docs ](https://docs.openssl.org/3.3/man3/SSL_read/#return-values)for [both](https://docs.openssl.org/3.3/man3/SSL_write/#return-values) say that 0 is an error.

This means that we end up returning 0 rather than going into either the retry logic or (as is appropriate for the case I've seen), [returning WGET_E_HANDSHAKE](https://github.com/rockdaboot/wget2/blob/ec27488feadd44b5e126592bc18ff2441f8cae5a/libwget/ssl_openssl.c#L1830). The calling function [wget_ssl_read_timeout](https://github.com/rockdaboot/wget2/blob/ec27488feadd44b5e126592bc18ff2441f8cae5a/libwget/ssl_openssl.c#L1859) then looks for `WGET_E_HANDSHAKE` to determine if it's an error and further up the stack, in `http2.c`, function [wget_http2_get_response_cb](https://github.com/rockdaboot/wget2/blob/ec27488feadd44b5e126592bc18ff2441f8cae5a/libwget/http2.c#L373), looks for `-1` (the value of `WGET_E_HANDSHAKE`) to break out of the loop it's in, which ends up being an infinite loop in the case I'm seeing.

I've created a draft pull request #343 as a potential fix for this.

**Comment by rockdaboot** [comment]
Thanks for the report :+1:
