### ISSUE TITLE
OCSP requests bodies are printed in debug output despite being binary

### ISSUE THREAD

**Issue by tobiasb-ms** [rockdaboot/wget2#344]
When the `--ocsp` and `--debug` are specified with an `openssl` `tls` provider, the `debug_skip_body` field is not set on the request, which causes the binary body of the request to printed to debug output. This can cause very interesting things with the command prompt, depending on the binary data being spewed out.

With `gnutls` as the `tls` provider, [the field is set properly](https://github.com/rockdaboot/wget2/blob/ec27488feadd44b5e126592bc18ff2441f8cae5a/libwget/ssl_gnutls.c#L636). But with `openssl`, it isn't.

I've created a draft pull request #345 as a potential fix for this.

**Comment by rockdaboot** [comment]
Fixed by #345
