### ISSUE TITLE
Can't build wget2 anymore (wolfssl 5.7.4, gcc 14.2)

### ISSUE THREAD

**Issue by sphoto** [rockdaboot/wget2#351]
Please see screenshot below.

![build_error](https://github.com/user-attachments/assets/8cb36284-04a0-44f0-8d9f-cd7a7cf8d20a)

With trailing semicolon in line 840 and 841 (ssl_wolfssl.c) wget builds successfully.

**Comment by rockdaboot** [comment]
Which compiler (including version) and which WolfSSL version are you using?

**Comment by rockdaboot** [comment]
With gcc 14.2.0 and WolfSSL 5.7.2 (Debian testing), there is no such issue.
The definition of `XFREE` here is
```
{void* xp = (p); (void)(h); (void)(t); if (xp) wolfSSL_Free(xp);}
```
Maybe that has been changed with 5.7.4. I'll try to check.

**Comment by rockdaboot** [comment]
OK, they changed it to
```
do { void* xp = (p); if (xp) wolfSSL_Free(xp, h, t); } while (0)
```
Which explains the error.
