### ISSUE TITLE
Support for SOCKS proxy

### ISSUE THREAD

**Issue by maaaaz** [rockdaboot/wget2#352]
Hello there,

Thanks for your great work!

Do you plan to add `wget2` SOCKS proxy support in a near future ?
Or at least make it compatible with `torsocks` ?

Cheers!

**Comment by rockdaboot** [comment]
> Do you plan to add wget2 SOCKS proxy support in a near future ?

I personally won't have time to do that, but highly appreciate any contributions.
But why not using torsocks?

> Or at least make it compatible with torsocks ?

I am not aware of problems with wget2 and torsocks. Please be more specific.

**Comment by maaaaz** [comment]
Indeed, it works well with torsocks, my bad.
