### ISSUE TITLE
Sync save file names between wget2 and wget1

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#36]
Wget1.x uses ~/.wget-hsts while Wget2 uses ~/.wget_hsts.
Which one to use ? I don't mind.

**Comment by juaristi** [comment]
Yes. Also, wget uses 0 in default ports (443 when https) in order to ease hsts policy matching later, whereas wget2 uses the port itself.

Sent from my smartphone. Excuse my brevity.

---- Tim Rühsen escribió ----

**Comment by rockdaboot** [comment]
If pull request #37 is ok for you, I'll pull it (maybe locally not via github).
It currently blocks this issue and my .netrc code.
But pulling means you have to adjust #33.
After that, we care for the port numbering.

**Comment by rockdaboot** [comment]
Since Wget 1.17 is released, ~/.wget_hsts and ~/.wget_ocsp have been adjusted to ~/.wget-hsts and ~/.wget-ocsp
