### ISSUE TITLE
^C causes a Core dump

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#4]
When trying to kill a running session of Wget2, the SIGINT signal is not handled correctly. As a result, the signal is passed on the various threads causing a Core Dump. SIGKILL and SIGTERM should both be gracefully handled in the ideal scenario.

**Comment by rockdaboot** [comment]
I can't reproduce it here on Debian SID. The process just stops with core dump.
Any special settings needed ?

**Comment by juaristi** [comment]
Wget saved the partially downloaded file when pressing Ctrl-C.
Later, it could resume the download from where it was left.

IMO that was a great feature. I propose to keep it.

On 10/16/2015 08:29 PM, Darshit Shah wrote:
> When trying to kill a running session of Wget2, the SIGINT signal is
> not handled correctly. As a result, the signal is passed on the
> various threads causing a Core Dump. SIGKILL and SIGTERM should both
> be gracefully handled in the ideal scenario.
>
> — Reply to this email directly or view it on GitHub
> <https://github.com/rockdaboot/wget2/issues/4>.
>

Regards,
- AJ

**Comment by darnir** [comment]
A core dump is exactly what I'm talking about. The process should not stop with a core dump, but rather it should stop stop downloading, try to join to the threads, and exit gracefully. 

Also, as Ander points out, maintain the partially downloaded file that can be resumed. So, importantly, we should attempt to close the file descriptor too.

**Comment by rockdaboot** [comment]
Sorry I wrote 'with', corrected to 'without' now. The SIGINT handler just has to set 'terminate' to 1. And that what it is doing. I'll have a look at it.

**Comment by rockdaboot** [comment]
The question is, how can we gracefully stop the threads.
While downloading files, the threads give control to the HTTP layer (wget_http_get_response() group of functions). We could add a new function to set a status variable address via a new function wget_http_set_term_condition(HTTP_CONNECTION *conn, int *term_condition).

The SIGINT handler sets term_condition=1 and the receive() loops check this variable and return if non-zero.

This is very easy to implement.

There is one case, where we have to take special care:
--chunk-size allows a multi-threaded download of a single file.
When pressing CTRL-C, several chunks are likely to have just a part of their current download data. To not have a damaged file when continuing the download, we must only save complete chunks or the data with the lowest file offset. In other words, we have to take care that there are no 'holes' in the saved file.

**Comment by rockdaboot** [comment]
Commit pushed, please check if it works for you.
I guess, I need a second branch to generate pull requests for review...

**Comment by darnir** [comment]
Yes. It does work fine now. And I particularly like how you allowed for termination of a single connection too.

**Comment by darnir** [comment]
EDIT: We need to have a test to ensure that the download isn't corrupted in this case.
