### ISSUE TITLE
tests/test.c fails on CygWin

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#40]
This is due to sprintf("%05s","abc") results in '00abc' on CygWin / Windows but it is expected to result in '  abc' as on glibc/Linux. We could simply skip this test when we know that sprintf prepends zeroes.
In the long term, we should make printf-style function to use the internal printf functions - it is faster than glibc but lacks floating point support for now.

**Comment by giuseppe** [comment]
this is another issue that can be solved using gnulib and the printf-posix module so that wget2 hasn't to maintain its own version of printf

**Comment by rockdaboot** [comment]
I have gnulib in mind.
Wget2's own version of printf is fast, has perfect test coverage, and is not much code.
My idea is to add special control sequences - e.g. %WH for human readable output (1.23G, 6.0M, ...) and/or %WQ for quoted strings. Just to make the code more readable and less error prone.
