### ISSUE TITLE
Add soon-to-come cookies security extensions

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#43]
From the curl mailing list (Daniel Stenberg):

> There are movements within the IETF to make a revision of the RFC 6265, known 
> as HTTP cookies.
> 
> The two current primary suggestion for changes are these:
> - https://tools.ietf.org/html/draft-west-leave-secure-cookies-alone-04
> - https://tools.ietf.org/html/draft-west-cookie-prefixes-05

**Comment by darnir** [comment]
I've implemented half of draft-west-leave-secure-cookie-alone-04 but ran into problems with the test suite. I'm also a little unsure about where these tests should be places. Currently, I've written the checks inside of wget_cookie_normalize_cookies, but it doesn't look like the best place to do so. 

My other option was wget_cookie_store_cookie, but that would require changing the API of libwget since these checks require the IRI of the cookie as well.

**Comment by rockdaboot** [comment]
> My other option was wget_cookie_store_cookie, but that would require changing the API of libwget since these checks require the IRI of the cookie as well.

Another option would be to extend the cookie structure by a flag 'secure_source' which can be set right after wget_http_parse_setcookie();

Like cookie->secure_source = iri->scheme == WGET_IRI_SCHEME_HTTPS;

Or add the flag as third param to wget_http_parse_setcookie !?

**Comment by darnir** [comment]
I think wget_http_parse_setcookie() should only do the parsing of the cookie.

The best place in my opinion is from `wget_cookie_store_cookie()`. We should extend the cookie structure as you suggested and run the tests in the store() method.

**Comment by rockdaboot** [comment]
> I think wget_http_parse_setcookie() should only do the parsing of the cookie.

I meant explicitly setting 'secure_source' after calling wget_http_parse_setcookie(), not inside.
But anyways, a places where we call wget_http_parse_setcookie() we do not have 'iri' available.

> The best place in my opinion is from wget_cookie_store_cookie(). We should extend the cookie structure as you suggested and run the tests in the store() method.

What about _wget_cookie_normalize_cookie() - as you already suggested ? This is used by wget_cookie_normalize() and wget_cookie_normalize_cookies() - and these have to be called before storing cookies. Only 'normalized' cookies are stored. And _wget_cookie_normalize_cookie() has 'iri' available. So your first idea is maybe the best.
