### ISSUE TITLE
Tests do not execute correctly

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#45]
Multiple issues when trying to run the test suite.

1. `make check` does not execute the tests correctly. It seems to be skipping some tests without a reason
2. Test results change based on the `$PWD` from which the test was executed.

Both the tests seem to be related to the same issue. The path to the PSL data file is relative, which causes these problems. 

There's also another issue that where `./tests/test` prints `(null)` as the result of two tests. This should not happen, and if it does, should be caught by the test suite at some point.

As of now a few PSL tests seem to be failing, but `make check` reports no errors, because it does not run the tests at all.

**Comment by rockdaboot** [comment]
> There's also another issue that where ./tests/test prints (null) as the result of two tests. This should
> not happen, and if it does, should be caught by the test suite at some point.

I am just working on the test suite (hashing failure with libnettle weren't caught).

> make check does not execute the tests correctly. It seems to be skipping some tests without a reason

Some of the FTP tests ? Not sure what tests you are talking about - how to reproduce ?

**Comment by darnir** [comment]
No, these are HTTP tests. In `./tests/test.c` the PSL data is not correctly initialized. Hence, those tests fail. But the file isn't able to catch the failures for some reason. For example, the contents of `./tests/test.log` is:

    0 XML, 0 HTML and 0 CSS files parsed
    (null)
    (null)
    (null)
    (null)
    ID=65=abcd
    ID=65=abcd
    ID=65=abcd
    (null)
    ID=65=abcd
    Summary: All 194984 tests passed
  PASS test (exit status: 0)

Whereas, the output generated when I execute `./tests/test` is:

    0 XML, 0 HTML and 0 CSS files parsed
    Failed [0]: PSL check(ID=65=abcd; expires=Tuesday, 07-May-2013 07:48:53 GMT; path=/;domain=.example.com; HttpOnly) -> -1 (expected 0)
    Failed [1]: PSL check(ID=65=abcd; expires=Tue May 07 07:48:53 2013; path=/; domain=.example.com) -> -1 (expected 0)
    Failed [2]: PSL check(ID=65=abcd; expires=Tue, 07-May-2013 07:48:53 GMT; domain=.example.com) -> -1 (expected 0)
    Failed [3]: PSL check(ID=65=abcd; expires=Tue, 07-May-2013 07:48:53 GMT; path=/) -> -1 (expected 0)
    Failed [4]: PSL check(ID=65=abcd) -> -1 (expected 0)
    Failed [5]: PSL check(ID=65=abcd; expires=Tue, 07-May-2013 07:48:53 GMT; path=/; domain=.example.org) -> -1 (expected 0)
    (null)
    (null)
    Failed [8]: PSL check(ID=65=abcd; path=/; domain=.educ.ar) -> -1 (expected 0)
    Summary: 7 out of 194984 tests failed

**Comment by darnir** [comment]
> I am just working on the test suite (hashing failure with libnettle weren't caught).

The errors I see are call caused inside check_cookie(). The issue is that the test fails, but none of the failure cases match. It eventually falls back to this statement:
```
info_printf("%s\n", header = wget_cookie_create_request_header(cookies, iri));
```
and `wget_cookie_create_request_header()` returns a NULL pointer

**Comment by rockdaboot** [comment]
> info_printf("%s\n", header = wget_cookie_create_request_header(cookies, iri));

Sorry, the printf() is a remnant. wget_cookie_create_request_header() / xfree is being called to provoke errors with valgrind. It may return a NULL value - that is not an error. It just means, there is no cookie stored for 'iri'.

**Comment by rockdaboot** [comment]
To make the DATADIR absolute just change tests/Makefile.am:
> -DEFS = @DEFS@ -DDATADIR=\"$(top_srcdir)/data\" -DSRCDIR=\"$(srcdir)\"
> +DEFS = @DEFS@ -DDATADIR=\"$(abs_top_srcdir)/data\" -DSRCDIR=\"$(srcdir)\"

./config.status && make check, now you can call tests/test

**Comment by darnir** [comment]
> Sorry, the printf() is a remnant. wget_cookie_create_request_header() / xfree is being called to 
> provoke errors with valgrind. It may return a NULL value - that is not an error. It just means, there is > to cookie stored for 'iri'.

In that case, would it be okay if we test the output for NULL before printing it? It would allow for a cleaner test output. I'll send a pull request for discussion
