### ISSUE TITLE
Use gnulib

### ISSUE THREAD

**Issue by giuseppe** [rockdaboot/wget2#46]
make wget2 use gnulib to solve portability and have access to other useful functions.

**Comment by darnir** [comment]
I agree. Using gnulib may be pretty beneficial for us. It provides some useful functions and takes care of a lot of portability problems for the library.

**Comment by rockdaboot** [comment]
Do we need the bootstrap.sh and bootstrap.conf ? Are these 'official' Gnu files and where can they be found ?

**Comment by rockdaboot** [comment]
I added gnulib, just with fcntl and strdup as gnulib_modules. Please add more (into ./autogen.sh right now) and someone please try to test it in an environment where gnulib is really needed.

**Comment by rockdaboot** [comment]
Sorry for being a bit 'rejective' regarding gnulib in the first place. I now started loving it...
