### ISSUE TITLE
Add certificate pinning

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#5]
see https://tools.ietf.org/html/rfc7469
We should support predefined lists and TOFU (Trust On First Use).
gnutls-client has TOFU support.

**Comment by juaristi** [comment]
I've started working on this. Expect a patch soon.

**Comment by juaristi** [comment]
This is all done and working on my side. In the following days I'll have a close scrutiny of the code to chase bugs before I send you a PR.

**Comment by rockdaboot** [comment]
Great ! If you push your code to Github, I can start reviewing it - I am in the office the next two days and hopefully have some time for it.

**Comment by juaristi** [comment]
Part of it is already pushed. Other bits are still in my computer. It's all in the [feature-hpkp](https://github.com/juaristi/wget2/tree/feature-hpkp) branch.

**Comment by rockdaboot** [comment]
Really cool ! I amended a few things and pushed it today to master.
