### ISSUE TITLE
Hide library symbols that are used internally only

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#51]
$ readelf -a libwget-0.0.1.so.0.0.0|grep "GLOBAL DEFAULT"|grep -v ' UND '|grep -v ' wget_'

   160: 00000000000102d0    98 FUNC    GLOBAL DEFAULT   12 yy_delete_buffer
   171: 0000000000020d80    17 FUNC    GLOBAL DEFAULT   12 rpl_malloc
   176: 000000000000f890   205 FUNC    GLOBAL DEFAULT   12 yypush_buffer_state
   180: 000000000000efc0   116 FUNC    GLOBAL DEFAULT   12 yy_flush_buffer
   196: 000000000001bd70    98 FUNC    GLOBAL DEFAULT   12 metalink3_parse
   212: 000000000000f860    37 FUNC    GLOBAL DEFAULT   12 yy_scan_string
   235: 000000000000f380   284 FUNC    GLOBAL DEFAULT   12 yylex_init_extra
   257: 000000000000db10    74 FUNC    GLOBAL DEFAULT   12 strlcpy
   259: 000000000000f1e0     5 FUNC    GLOBAL DEFAULT   12 yyset_out
   274: 000000000000f1d0     5 FUNC    GLOBAL DEFAULT   12 yyset_in
   276: 00000000000102c0     5 FUNC    GLOBAL DEFAULT   12 yyfree
   280: 000000000000f220   116 FUNC    GLOBAL DEFAULT   12 yy_create_buffer
   308: 000000000000f2a0   218 FUNC    GLOBAL DEFAULT   12 yylex_init
   345: 000000000000f160     4 FUNC    GLOBAL DEFAULT   12 yyset_extra
   346: 000000000000f960  2385 FUNC    GLOBAL DEFAULT   12 yylex
   352: 000000000000f140     5 FUNC    GLOBAL DEFAULT   12 yyget_leng
   353: 000000000000f0b0     4 FUNC    GLOBAL DEFAULT   12 yyget_extra
   362: 000000000000f7d0   140 FUNC    GLOBAL DEFAULT   12 yy_scan_bytes
   374: 000000000000f640   194 FUNC    GLOBAL DEFAULT   12 yy_switch_to_buffer
   395: 000000000001bd00    98 FUNC    GLOBAL DEFAULT   12 metalink4_parse
   400: 000000000000f130     5 FUNC    GLOBAL DEFAULT   12 yyget_out
   406: 0000000000010340   146 FUNC    GLOBAL DEFAULT   12 yypop_buffer_state
   407: 00000000000103e0   223 FUNC    GLOBAL DEFAULT   12 yylex_destroy
   419: 000000000000f170    48 FUNC    GLOBAL DEFAULT   12 yyset_lineno
   421: 0000000000020da0    17 FUNC    GLOBAL DEFAULT   12 rpl_realloc
   442: 000000000000f0c0    35 FUNC    GLOBAL DEFAULT   12 yyget_lineno
   453: 000000000000f580   181 FUNC    GLOBAL DEFAULT   12 yyrestart
   458: 000000000000f1a0    48 FUNC    GLOBAL DEFAULT   12 yyset_column
   472: 000000000000f0f0    35 FUNC    GLOBAL DEFAULT   12 yyget_column
   484: 0000000000234ae0    16 OBJECT  GLOBAL DEFAULT   20 iri_ports
   529: 000000000000f200     7 FUNC    GLOBAL DEFAULT   12 yyset_debug
   530: 000000000000f150     8 FUNC    GLOBAL DEFAULT   12 yyget_text
   533: 000000000000f1f0     7 FUNC    GLOBAL DEFAULT   12 yyget_debug
   547: 000000000000f710   185 FUNC    GLOBAL DEFAULT   12 yy_scan_buffer
   559: 000000000000f120     5 FUNC    GLOBAL DEFAULT   12 yyget_in
   573: 000000000000f4a0     5 FUNC    GLOBAL DEFAULT   12 yyrealloc
   576: 000000000000f210     5 FUNC    GLOBAL DEFAULT   12 yyalloc
   237: 000000000000f640   194 FUNC    GLOBAL DEFAULT   12 yy_switch_to_buffer
   250: 000000000000f580   181 FUNC    GLOBAL DEFAULT   12 yyrestart
   251: 000000000000f0f0    35 FUNC    GLOBAL DEFAULT   12 yyget_column
   270: 000000000000f130     5 FUNC    GLOBAL DEFAULT   12 yyget_out
   300: 000000000001bd00    98 FUNC    GLOBAL DEFAULT   12 metalink4_parse
   366: 000000000000f1f0     7 FUNC    GLOBAL DEFAULT   12 yyget_debug
   379: 000000000000f4a0     5 FUNC    GLOBAL DEFAULT   12 yyrealloc
   384: 000000000000f220   116 FUNC    GLOBAL DEFAULT   12 yy_create_buffer
   432: 000000000000f150     8 FUNC    GLOBAL DEFAULT   12 yyget_text
   437: 000000000000f210     5 FUNC    GLOBAL DEFAULT   12 yyalloc
   451: 00000000000102c0     5 FUNC    GLOBAL DEFAULT   12 yyfree
   452: 000000000000f170    48 FUNC    GLOBAL DEFAULT   12 yyset_lineno
   459: 000000000000f710   185 FUNC    GLOBAL DEFAULT   12 yy_scan_buffer
   482: 000000000000f380   284 FUNC    GLOBAL DEFAULT   12 yylex_init_extra
   485: 000000000000f860    37 FUNC    GLOBAL DEFAULT   12 yy_scan_string
   487: 000000000000f1d0     5 FUNC    GLOBAL DEFAULT   12 yyset_in
   495: 000000000000f7d0   140 FUNC    GLOBAL DEFAULT   12 yy_scan_bytes
   506: 000000000000f0c0    35 FUNC    GLOBAL DEFAULT   12 yyget_lineno
   521: 000000000000f140     5 FUNC    GLOBAL DEFAULT   12 yyget_leng
   529: 000000000000f890   205 FUNC    GLOBAL DEFAULT   12 yypush_buffer_state
   565: 00000000000102d0    98 FUNC    GLOBAL DEFAULT   12 yy_delete_buffer
   572: 0000000000020d80    17 FUNC    GLOBAL DEFAULT   12 rpl_malloc
   604: 0000000000010340   146 FUNC    GLOBAL DEFAULT   12 yypop_buffer_state
   612: 000000000000f0b0     4 FUNC    GLOBAL DEFAULT   12 yyget_extra
   614: 000000000000db10    74 FUNC    GLOBAL DEFAULT   12 strlcpy
   625: 000000000000f1a0    48 FUNC    GLOBAL DEFAULT   12 yyset_column
   629: 000000000000f160     4 FUNC    GLOBAL DEFAULT   12 yyset_extra
   662: 000000000000f960  2385 FUNC    GLOBAL DEFAULT   12 yylex
   688: 000000000000efc0   116 FUNC    GLOBAL DEFAULT   12 yy_flush_buffer
   716: 000000000000f2a0   218 FUNC    GLOBAL DEFAULT   12 yylex_init
   732: 000000000000f120     5 FUNC    GLOBAL DEFAULT   12 yyget_in
   734: 000000000001bd70    98 FUNC    GLOBAL DEFAULT   12 metalink3_parse
   755: 0000000000234ae0    16 OBJECT  GLOBAL DEFAULT   20 iri_ports
   770: 000000000000f200     7 FUNC    GLOBAL DEFAULT   12 yyset_debug
   772: 000000000000f1e0     5 FUNC    GLOBAL DEFAULT   12 yyset_out
   791: 0000000000020da0    17 FUNC    GLOBAL DEFAULT   12 rpl_realloc
   793: 00000000000103e0   223 FUNC    GLOBAL DEFAULT   12 yylex_destroy

I removed _* symbols from the list, used by the library itself. But I guess all the others should be hidden. This has to go into libwget.h:

```C
#if _GCC_VERSION_AT_LEAST(4,0)
#  define _HIDDEN __attribute__ ((visibility ("hidden")))
#else
#  define _HIDDEN
#endif
```

Not sure how to tell flex to add this to the yylex functions.

**Comment by juaristi** [comment]
For me, it's a whole lot easier to do it the other way round. Tell GCC to hide everything and explictly mark the functions you want to make public. You do that by passing `-fvisibility=hidden`, and marking the public functions explicitly:

```
#define LIBWGET_API __attribute__ ((visibility("default")))
```

More info in the [GCC docs](https://gcc.gnu.org/onlinedocs/gcc-4.3.3/gcc/Code-Gen-Options.html#index-fvisibility-1922).

**Comment by darnir** [comment]
I like Ander's approach. It's cleaner and more explicit about the functions
being exposed

Thanking You,
Darshit Shah

**Comment by rockdaboot** [comment]
@juaristi You are definitely right. That's how we should do it.

**Comment by rockdaboot** [comment]
I have it done, but there is one issue with gnulib (/usr/bin/ld: test_linking: hidden symbol `rpl_fcntl' in ../lib/libgnu.a(fcntl.o) is referenced by DSO). I already asked on the bug-gnulib mailing list. I have no idea what is going on...

**Comment by rockdaboot** [comment]
It was --libtool option of gnulib-tool that was missing plus some tweaks in the different Makefile.am.
The changes are pushed.
