### ISSUE TITLE
Handle large files correctly

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#52]
I never made downloads of files >= 2^31 or >=2^32 - we should set up a test script in the contrib/ directory and for Travis. Having this in 'make check' would take too long, I guess.

Wget2 currently downloads into memory - and saves the file to disk only if requested. It it parses files (HTML, CSS, robots.txt, sitemaps on -r) in memory. I see two points that have to be addressed:

  * files not to be parsed could go directly (or with a small memory caching) to disk.
  * files to be parsed should have an upper size to avoid DOS attacks, e.g. if a CSS file becomes > 10MB, we save the file to disk without parsing. WDYT ?

**Comment by juaristi** [comment]
Yes, but no parsing means not following links, right?

It's a good idea. What I'd do is hardcode a default upper size limit (ie. 10MB), but let the user override it if they wish.

**Comment by rockdaboot** [comment]
10mb are exactly what I had in mind :-)

**Comment by giuseppe** [comment]
this is a serious issue.  We should write to file as soon as possible, as wget can crash, especially with big files, and the file will never be downloaded.  We should not keep the file in ram when it is not needed.

**Comment by rockdaboot** [comment]
Closing thanks to Giuseppe latest commits.

**Comment by giuseppe** [comment]
It doesn't still handle multiple parts. I am going to take a look at it
