### ISSUE TITLE
Support HSTS preloaded lists from external sources

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#66]
Common browsers have their own HSTS lists. Wget2 should be able to read them (directly or via a conversion tool). Maybe we provide a conversion tool that generates a DAFSA dictionary, that can be taken as input via a new CLI option ?

Chromium's list needs support for JSON format:
[Chromium HST Preload List](https://code.google.com/p/chromium/codesearch#chromium/src/net/http/transport_security_state_static.json)
[Official place?](https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json)

Mozilla has it in C source code:
[Mozilla Preload List](https://dxr.mozilla.org/mozilla-central/source/security/manager/ssl/nsSTSPreloadList.inc)

**Comment by darnir** [comment]
I'm not entirely sure about this. A conversion tool that can convert from Chromium's JSON or Mozilla's C source sounds nice, but I would convert them to the same format in which Wget's own HSTS lists are written. Then passing it to Wget2 on invokation is simply passing the standard --hsts-file option.

Also, if we add such support, then Wget2 should support multiple --hsts-file command line options. The reason for that is to allow the .wgetrc to contain a system-wide hsts file provide by the sysadmin and yet allow the user to supply their own HSTS files. I'm not sure if this is already possible, but it would be important.

With the large Mozilla and Chromium HSTS lists, it may make sense to generate a precompiled DAFSA dictionary with Wget2.

**Comment by rockdaboot** [comment]
I have to mention that Mozilla's and Chromium's lists are pretty the same.

> Also, if we add such support, then Wget2 should support multiple --hsts-file command line options.
We can also allow '+' or '-' in front of the file name to have 'add', 'remove' and 'set' (set = what we do now). This could be useful for many options.

> With the large Mozilla and Chromium HSTS lists, it may make sense to generate a precompiled DAFSA dictionary with Wget2.
Yes, I thought about it. I am now sure if there is GNU source code to generate DAFSA/DAWG and to lookup entries. I couldn't find it yet - I'll ask the GNU veterans the next days.

**Comment by darnir** [comment]
> We can also allow '+' or '-' in front of the file name to have 'add', 'remove' and 'set' (set = what we do now). This could be useful for many options.

This is a good idea. We could allow this.

> Yes, I thought about it. I am now sure if there is GNU source code to generate DAFSA/DAWG and to lookup entries. I couldn't find it yet - I'll ask the GNU veterans the next days.

I don't think I've seen any other DAFSA utilities. We could keep using the one from Chromium that is used for Libpsl here as well. The licensing shouldn't be an issue either.

In fact, the script need not be available in the release tarballs either. When making a release, only the generated file needs to be packaged.
