### ISSUE TITLE
Consider RFC 7230

### ISSUE THREAD

**Issue by rockdaboot** [rockdaboot/wget2#67]
[RFC 7230](https://tools.ietf.org/html/rfc7230) clarifies many aspects of HTTP (see A.2. for a summary of changes).

E.g. the use of Proxy-Connection header is discouraged (see A.1.2.), while we still use it as default (also Wget 1.x). 

Looks like curl is going to remove it (Firefox already removed it) - that's why I opened this issue.

**Comment by darnir** [comment]
You're right,. If we're not following 7230 entirely yet, we should. Hence, marking this as a bug.

**Comment by rockdaboot** [comment]
Well, it is not a bug if you don't follow it. There is a lot of server software out there that might not communicate with us, if we obey the RFC in all points.

I would suggest that you open a bug / enhancement issue for exactly each point you find worth it in the RFC. This issue is just a general hint to read the RFC and consider it. So I mark it as 'help wanted'. I hope you agree :-)

**Comment by darnir** [comment]
I guess you could say that. I was being naive in trying to follow the RFC entirely, then I remembered all the kludges in Wget 1.x for supporting errant servers.

I'll open separate issues for specific points later.

**Comment by rockdaboot** [comment]
Re-reading the RFC basically reduces the changes for Wget2 to remove Proxy-Connection.
I just commented out the code, leaving it with a pointer to RFC 7230 A.1.2..
