### ISSUE TITLE
Progress bar is broken

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#7]
This is not a blocker, but the progress bar simply doesn't work. In fact with the `--progress` option, Wget2 will not download any file. This is a major issue since it is no longer simply aesthetic. It now interferes with the normal functioning of Wget2.

**Comment by rockdaboot** [comment]
Yes, the progress bar code is just a starter. You are the expert here. I suggest, we should move parts of the Wget code into Wget2. I am definitely the wrong person for progress bars :-(

**Comment by darnir** [comment]
Only some parts. The Wget progress bar code is not very thread safe. We sure can import the code that handles constructing the bar. It's quite robust.

But before that, there are a bunch of other issues that we need to resolve. Enabling the progress bar causes the download to fail. 

Also, we should discuss and come to a consensus on how the progress bar should be implemented. I'll draft a small article on how I think the progress bars should work. We can then debate on that.

**Comment by darnir** [comment]
The progress bar has been fixed for quite some time now. It is not the best out there, but it works. So I'm closing this issue.
