### ISSUE TITLE
Use `bootstrap` instead of `autogen.sh`

### ISSUE THREAD

**Issue by juaristi** [rockdaboot/wget2#76]
In my workplace, the edge firewall blocks pretty much any port different than 80/443/53. Thus, with wget I would run:
```
./bootstrap --gnulib-srcdir=../gnulib --no-bootstrap-sync --no-git --skip-po --copy
```
So that it grabs the pre-downloaded gnulib sources from `../gnulib` and doesn't attempt to download them from the Internet through a not-so-well-known `git://` port.
This is just a specific use case, I'm not expecting you to tell my sysadmins to disable the firewall!

What I would like is that `./autogen.sh` accept the same command line options as `bootstrap` does.

`./autogen.sh` does not react to those options. I think it's ignoring them all. I don't really know what's the difference between both files. Searching the web seems like they do virtually the same thing, and they're both from gnulib, but I couldn't find much more info apart from that.

**Comment by rockdaboot** [comment]
./autogen.sh is just a little shell script from me (taken over from 'mget' and expanded).
You can simply remove the git submodule stuff from there and simply copy the gnulib directory from anywhere you like.
OR: change the path in .gitmodules from 'git://' to 'https://'.
OR: remove the git submodule with 'git deinit gnulib'
OR: configure git to use a (HTTP) proxy

**Comment by rockdaboot** [comment]
Can you try this:
 * clone wget2
 * execute `git clone http://git.savannah.gnu.org/r/gnulib.git`
 * `./autogen.sh`

**Comment by juaristi** [comment]
Oh, yes. But the intent of this issue is to discuss whether we could just use `bootstrap`. In addition to the command line options, it also gives us the advantage of being able to put the dependencies in `bootstrap.conf`, rather than hard-coded in the shell script itself. I mean, I shouldn't be doing nasty changes in the scripts. WDYT?

**Comment by juaristi** [comment]
So far, I found the best explanation of what `bootsrap` does in the source code comments of the script itself:
```
The canonical version of this
script is maintained as build-aux/bootstrap in gnulib, however, to
be useful to your project, you should place a copy of it under
version control in the top-level directory of your project.  The
intent is that all customization can be done with a bootstrap.conf
file also maintained in your version control; gnulib comes with a
template build-aux/bootstrap.conf to get you started.
```
I read there used to be some relationship in the past between `autogen.sh` and `bootstrap`, but now looks like the former has been deprecated.

**Comment by rockdaboot** [comment]
autogen.sh and bootstrap are both fine. 
The question is, what does bootstrap provide they we are missing ? Or: what exactly is broken right now ?
bootstrap.conf is being 'sourced', executed like a script.
If you want a bootstrap.conf, you can move the list of modules from autogen.sh to bootstrap.conf and voila. But since almost no developer ever looks into these files, I don't see any gain in it.

Also, I couldn't find any real docs for bootstrap. And looking into it, it is not understandable to me what *exactly* it does under certain conditions. How can we maintain such a thing ? I can't. Can you ?

If you badly want it, you should have good arguments. Right now, I am not convinced.
And bootstrap seems to have some issues... look at bootstrap.conf of wget1.x and tell me what `use_libtool=0` means. Not to use libttool ? If that were true, how comes that we need LTLIBICONV (the libtool variant of LIBICONV) in src/Makefile.am (see bug #48193) ? Where is that documentation that makes this clear ?

Sometimes, taking the 'small car' with less features is more elegant.

**Comment by giuseppe** [comment]
I am slightly in favor of`bootstrap` as the same script is used by few other projects and can be used as it is without modifications or caring of maintaining it.

I use bootstrap mainly for two things:

1) sync the gnulib modules -- something that can be easily done with gnulib/gnulib-tool anyway and..
2) sync .po files from translationproject.

Historically autogen.sh was just a wrapper around the autotools, something that can be easily done with `autoreconf -if`.

I think that `use_libtool` is initialized by the bootstrap script itself when it detects that configure.ac is using libtool.

**Comment by rockdaboot** [comment]
> 1) sync the gnulib modules

How exactly  ? I can't find an option for that.
Where are the docs for 'bootstrap` ?

> 2) sync .po files from translationproject

Automatically done by `bootstrap` ?

> I think that use_libtool is initialized by the bootstrap script itself when it detects that configure.ac is using libtool.

`bootstrap` sets `use_libtool` to 1 if it detects LT_INIT or A[CM]_PROG_LIBTOOL in configure.ac. Wget1.x does not have either... so again, why $(LTLIBICONV) for src/Makefile.am instead of $(LIBICONV).

Let me suggest:
- we need some kind of documentation for bootstrap and bootstrap.conf
- we need review (and possibly update) of both for Wget1.x first - hopefully to get some more insights during that process.

**Comment by rockdaboot** [comment]
Just found a rewrite of `bootstrap` including docs. Please have a look at it...
https://github.com/gnulib-modules/bootstrap

**Comment by giuseppe** [comment]
I don't know if there is any documentation for bootstrap, I never cared to look at it as it just works for me.  What problems exactly you had with it?

The autogen.sh in wget2 already sync the modules from gnulib with gnulib/gnulib-tool.

Yes, the .po files are fetched with rsync by the bootstrap script.

My observation was more that `autogen.sh` normally does just what `autoreconf -if` does, while the other operations should stay in a different script, that for gnulib based projects usually is bootstrap.  Using bootstrap would mean share more code with other projects that we don't need to maintain alone

**Comment by rockdaboot** [comment]
Ok, after thinking back and forth... @juaristi Would you like to create a patch ?

Still, we should find an answer to this, both for Wget 1 and 2:
> bootstrap sets use_libtool to 1 if it detects LT_INIT or A[CM]_PROG_LIBTOOL in configure.ac. Wget1.x does not have either... so again, why $(LTLIBICONV) for src/Makefile.am instead of $(LIBICONV) ?

Basically the question is: should we add $(LTLIBICONV) or $(LIBICONV) or both to src/Makefile.am ?

**Comment by juaristi** [comment]
This is a mess. I wasted close to one hour to figure out almost nothing. There are no docs, and I couldn't find any *clear* reason why things are split into LTLIB* and LIB*, neither in the gnulib mailing list nor in the commit messages. Just some mentions here and there, but no clear reason why things are done that way.

> bootstrap sets use_libtool to 1 if it detects LT_INIT or A[CM]_PROG_LIBTOOL in configure.ac. Wget1.x does not have either... so again, why $(LTLIBICONV) for src/Makefile.am instead of $(LIBICONV) ?
The answer is in m4/lib-link.m4. It searches for libraries in several pre-defined folders and defines either LIBICONV or LTLIBICONV. Starts at line 372, good luck if you want to try to look at it.

This problem was introduced very recently, by a user called ilovezfs, in the mailing list. Now, my question is, is this a `bootstrap`-specific problem? If yes, we could use the bootstrap replacement you mention, or stay with your autogen.sh, maybe mimicking the .po files download feature, which shouldn't be too hard. If no, well... we should probably reproduce the changes of Tim's patch at #48193.

As I said, much time for almost nothing.

**Comment by juaristi** [comment]
I think Guiseppe has succinctly explained us the benefits of bootstrap. But there are some issues I'm thinking of:
- Any time bootstrap is updated upstream we have to do things like in 43359f4 (Tim Rühsen, 13 June). This is not very maintainer-friendly.
- `bootstrap` is located at `build-aux/`, whereas in our tree it is at the root folder. What's the expected workflow? Copy it every time from `build-aux/` to our root?

I'm thinking maybe we could use the new bootstrap at https://github.com/gnulib-modules/bootstrap, put it `.gitmodules` and then in `autogen.sh` just do `git submodule init && git submodule update` and finally run `./bootstrap` and let it do the rest.

**Comment by rockdaboot** [comment]
I *guess* that LIBICONV / LTLIBICONV and bootstrap are two things though they both come from gnulib (gnulib and gettext both supply a version of lib-link.m4, slightly different here).

bootstrap is mentioned in the gnulib docs (https://www.gnu.org/software/gnulib/manual/gnulib.pdf), but not documented itself.

> Any time bootstrap is updated upstream we have to do things like in 43359f4 (Tim Rühsen, 13 June). This is not very maintainer-friendly.

Well, this is every few years... or maybe regularly after a release.

> bootstrap is located at build-aux/, whereas in our tree it is at the root folder. What's the expected workflow? Copy it every time from build-aux/ to our root? Or is there anything else?

Yes, after updating gnulib, we have to copy it from lib/build-aux. That's it.
I read some discussion about having a self-provided autogen/bootstrap in the project root which calls the gnulib bootstrap. Just can't find the discussion now. But this would obsolete the manual task of copying bootstrap from time to time.

To get a proper advise, we could ask on the gnulib mailing list.

And meanwhile we simply take the gnulib bootstrap. Than we have the same workflow as with Wget1. And we know bootstrap works for us and many others. It would be nice to get it right, but it needs someone with time and the will to discuss the whole thing with the gnulib maintainers. I am not the one right now.

**Comment by rockdaboot** [comment]
But I am going to ask about LIBICONV / LTLIBICONV.

**Comment by juaristi** [comment]
Yes, thanks @rockdaboot. I'm following the conversation on the mailing list. Looks like they're telling you "it's some sort of internal mechanism - you shouldn't care". But libiconv is already included in GNU systems. Yesterday I noticed no `-liconv` is ever passed on any of my computers, and both LIBICONV and LTLIBICONV are disabled. This is because `iconv()` is part of glibc since 2.1, so it is included in reasonably new GNU systems and just linking against libc is enough. This is something that affects non-GNU systems. We should state that clearly. Bug report #48193 was specifically targeting a Mac, I guess, judging by the output, although not stated by the reporter.

And once we solve this, there's nothing else left, is it? I would go no further trying to "get it right" with bootstrap. As you and Guiseppe said, it just works. Having said this, I'm not against using your autogen.sh, or the new bootstrap replacement. Any should work.

**Comment by rockdaboot** [comment]
@juaristi Please go ahead with bootstrap (the gnulib one). The LT discussion has nothing (or not much) to do with it. We can solve that for us in one or another way later.

BTW, I just pushed a change to autogen.sh and added a custom lib/Makefile.am. Please make sure you pull it before starting to work on the bootstrap thing (or at least consider those changes).

libiconv isn't integrated into libc on several systems. I tested Solaris 11 yesterday - here both variables (LT and non-LT variant) are set to '-liconv'. Have to test OpenBSD yet.

**Comment by juaristi** [comment]
OK. I'll try to send a PR next week.
> libiconv isn't integrated into libc on several systems. I tested Solaris 11 yesterday - here both variables (LT and non-LT variant) are set to '-liconv'. Have to test OpenBSD yet.

Yes, I know. That's why we're dealing with this problem.

**Comment by rockdaboot** [comment]
Fixed a few little things (e.g. bootstrap writes into .gitignore, SKIP_PO must be uppercase, amended commit message).
But the big thing is that po/Makevars.template is always overwritten (by autopoint --force called by bootstrap). And we need it to set MSGID_BUGS_ADDRESS to bug-wget@gnu.org instead of bug-wget2@gnu.org. Or is there anything else I miss ? Any idea where to set out mailing list address ?

**Comment by rockdaboot** [comment]
Pushed it with some more small changes. Thanks  for your work !
