### ISSUE TITLE
Test-i-https fails

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#8]
The test-i-https test seems to be failing for me.

The log output on the test is: 

> resolving localhost:(null)...
> has ::1:0
> has 127.0.0.1:0
> try to listen on ::1:0...
> insecure listen on ::1:36115...
> resolving localhost:(null)...
> has ::1:0
> has 127.0.0.1:0
> try to listen on ::1:0...
> secure listen on ::1:44595...
> resolving localhost:(null)...
> has ::1:0
> has 127.0.0.1:0
> try to listen on ::1:0...
> insecure listen on ::1:34154...
> resolving localhost:(null)...
> has ::1:0
> has 127.0.0.1:0
> try to listen on ::1:0...
> secure listen on ::1:45583...
> 
>   Testing '../../src/wget2 --ca-certificate=.././certs/x509-ca-cert.pem --no-ocsp -i urls.txt 2>&1'
> GnuTLS server init
> GnuTLS server init done
> WARNING: The certificate's (stapled) OCSP status has not been sent
> Server handshake completed

However, I must add that the output isn't very predictable. The number of times, the WARNING message appears is fairly random. But it appears alteast once. Also, *sometimes*, there will be another message indicating that it downloaded the file. However, even then the exit code is 141 which implies a failure.

**Comment by rockdaboot** [comment]
Just a guess, since it is not reproducible here: either same as #6 or a GnuTLS 3.4.x issue.
I just found 3.4.4 packaged for Debian unstable... I am going to test it.

**Comment by rockdaboot** [comment]
Just pushed a commit to comment the problematic code path.
I 'invented' it to use less CPU cycles for HTTP/2, but it seems not worth the hassle.
