### ISSUE TITLE
Building on ubuntu fails, undefined reference to `yylex_init'

### ISSUE THREAD

**Issue by Jaaap** [rockdaboot/wget2#95]
On my Ubuntu 16.04 xenial box, i installed a bunch of packages:
`sudo apt install libgcrypt11-dev libpsl-dev gnutls-dev libbz2-dev zlib1g-dev liblzma-dev libidn2-0-dev libidn11-dev libunistring-dev libnghttp2-dev gettext flex autotools-dev autoconf autopoint autogen`
and a bunch more without the -dev suffix.

When i run `make`, it gives this output:
`  CC       libwget_la-xml.lo`
`xml.c: In function 'parseXML':`
`xml.c:344:13: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector]`
` static void parseXML(const char *dir, XML_CONTEXT *context)`
`             ^`
`  CC       libwget_la-http_highlevel.lo`
`  CCLD     libwget.la`
`  CC       test_linking-test_linking.o`
`  CCLD     test_linking`
`./.libs/libwget.so: undefined reference to 'yylex_init'`
`./.libs/libwget.so: undefined reference to 'yy_scan_string'`
`./.libs/libwget.so: undefined reference to 'yyget_leng'`
`./.libs/libwget.so: undefined reference to 'yyget_text'`
`./.libs/libwget.so: undefined reference to 'yylex_destroy'`
`./.libs/libwget.so: undefined reference to 'yylex'`
`collect2: error: ld returned 1 exit status`
`Makefile:1489: recipe for target 'test_linking' failed`
`make[2]: *** [test_linking] Error 1`
`make[2]: Leaving directory '/home/******/wget2/wget2/libwget'`
`Makefile:1492: recipe for target 'all-recursive' failed`
`make[1]: *** [all-recursive] Error 1`
`make[1]: Leaving directory '/home/******/wget2/wget2'`
`Makefile:1401: recipe for target 'all' failed`
`make: *** [all] Error 2`

Any hints on what i'm doing wrong?

**Comment by rockdaboot** [comment]
Do you have package 'flex' installed ?

**Comment by rockdaboot** [comment]
```
$ dpkg -l '*flex*'
ii  flex                            2.6.1-1              amd64                fast lexical analyzer generator
```

After the ./configure run
```
$ grep LEX= config.log
ac_cv_prog_LEX=flex
LEX='flex'
```

**Comment by Jaaap** [comment]
```
~/wget2/wget2$ sudo apt install flex
[sudo] password for teun: 
Reading package lists... Done
Building dependency tree
Reading state information... Done
flex is already the newest version (2.6.0-11).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
```
```
~/wget2/wget2$ dpkg -l '*flex*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                               Version                Architecture           Description
+++-==================================-======================-======================-=========================================================================
ii  flex                               2.6.0-11               amd64                  fast lexical analyzer generator
un  flex-old                           <none>                 <none>                 (no description available)
```
```
~/wget2/wget2$ grep LEX= config.log
ac_cv_prog_LEX=flex
LEX='flex'
```

**Comment by rockdaboot** [comment]
*scratch*
I just have a fresh Mate64 (14.04) VM here with all commands (apt-get) still in history:
- apt-get install gcc automake autoconf flex make gettext
- apt-get install makeinfo texinfo autopoint gnutls-dev gnutls28-dev openssl-dev libssl-dev
(maybe some of them not needed - can't see the output any more)

After that, a fresh git clone, ./bootstrap, ./configure, make worked like charm.
(You made a git clone, right ? Or did you download some tarball ?)

**Comment by rockdaboot** [comment]
If that still doesn't work out... let me see the last lines of the ./configure run.
Also 'make clean' and show me the output of 'make' - there must be an error message that could help.

**Comment by Jaaap** [comment]
Yes that worked. I suspect the clean clone did it.
Now we're almost there.
```
~/wget2/wget2$ /usr/local/bin/wget2
/usr/local/bin/wget2: error while loading shared libraries: libwget.so.0: cannot open shared object file: No such file or directory
```
It does work when i add /usr/local/lib to my LD_LIBRARY_PATH:
`export LD_LIBRARY_PATH=/usr/local/lib`

now it works!

thanks for your help.
