### ISSUE TITLE
Add tests that use the progress bar

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#98]
The test suite needs to test the progress bar as well. Especially after the experience we've gained from implementing the progress bar in GNU Wget, we know that this section of the code requires some regression testing as well.

One idea is to add a --force-progress or similar switch which forces a display of the progress bar (similar to --show-progress in Wget) and then make sure that the output wget2 generates matches the expected progress bar output. This will also help us test the code more thoroughly and make sure there are no synchronization bugs.

**Comment by rockdaboot** [comment]
--progress=bar,force ?

**Comment by rockdaboot** [comment]
Wget1 has --progress=bar:force
We should go with that.
