### ISSUE TITLE
Old downloads disappear from progress output after error_printf()

### ISSUE THREAD

**Issue by darnir** [rockdaboot/wget2#99]
If wget2 generates any error and calls `error_printf()`while progress bar printing is enabled, then a custom logger is used to ensure that the right message is printed on top of the progress bars.

However, since the context of the downloads that have completed has been destroyed, those progress bars are lost and we see blank spaces on the screen.

There are two options to resolve this:

1. Don't destroy the context until either a new one replaces it in the `bar->slot` or the progress bar is destroyed itself
2. Display the messages at the end of the progress bars.

While option 2 looks elegant and simple, there are quite a few issues I see in there. 

1. If the number of errors exceeds the number of rows on the screen, then all calculation will be messed and we'll have garbage on the screen
2. We need to ensure that a new slot will never be added to the progress bars for printing
3. We need to keep track of the number of error messages printed to ensure that we print exactly one below.

**Comment by rockdaboot** [comment]
IMO, we should go with 1. (Don't destroy...). That would also allow a redraw when the screen becomes resized.
